pkg/ansibleapp/dockerhub_registry.go
* Need to continue the channel reader on an error
* Log the broken image
=> Bugfix to prevent crashing on bad images in an org

README.md, pkg/ansibleapp/types_test.go
"make test" was failing, looks like issue was with the "parameters:<nil>" now being part of subjectMap.
I added some sample parameters to the test data.
Original
$ make test
go test ./pkg/...
--- FAIL: TestSpecDumpJSON (0.00s)
util.go:55: false is not true!
FAIL
FAIL    github.com/fusor/ansible-service-broker/pkg/ansibleapp  0.020s
?       github.com/fusor/ansible-service-broker/pkg/app [no test files]
?       github.com/fusor/ansible-service-broker/pkg/broker      [no test files]
?       github.com/fusor/ansible-service-broker/pkg/dao [no test files]
?       github.com/fusor/ansible-service-broker/pkg/errors      [no test files]
?       github.com/fusor/ansible-service-broker/pkg/fusortest   [no test files]
?       github.com/fusor/ansible-service-broker/pkg/handler     [no test files] …
=> Updated types_test for Parameters

pkg/app/app.go
Previously, if the HTTP server couldn't bind to port 1338, the program would just terminate with a 0 exit code. Now it prints the error and exits with exit code 1.
=> Print error when HTTP server can't start

ansible/main.yml, docker/entrypoint.sh, pkg/ansibleapp/client.go, pkg/ansibleapp/provision.go, pkg/broker/broker.go, pkg/broker/types.go
* Entrypoint permission corrections
* Read correct property out of config
* Accept ansibleapp.Parameters instead of map[string]string for params
in provision request. map[string]interface{} is the recommended type for
generic JSON. ansibleapp.Parameters is a typedef for this.
* Some better debug logging
=> Containerization bugfixes

cmd/broker/main.go, cmd/mock-registry/mock_registry.go, pkg/ansibleapp/bind.go, pkg/ansibleapp/bind_test.go, pkg/ansibleapp/client.go, pkg/ansibleapp/dev_registry.go, pkg/ansibleapp/hack.go, pkg/ansibleapp/provision.go, pkg/ansibleapp/registry.go, pkg/ansibleapp/rhcc_registry.go, pkg/ansibleapp/types.go, pkg/app/args.go, pkg/app/config.go, pkg/app/logger.go, pkg/broker/broker.go, pkg/broker/hacks.go, pkg/broker/util.go, pkg/dao/dao.go, pkg/handler/io.go
I used goimport from vim-go to reorder the imports. To configure it on your machine add this to your `.vimrc` file:
* Replace `fatih/vim-go` with 'jmrodri/vim-go`.
* Configure vim-go to use goimports:
`let g:go_fmt_command = "goimports"`
=> use goimports to reorder and cleanup imports

ansible/main.yml
```
> $ ./asbcli up --cluster-user admin --dockerhub-user jcpowermac openshift.virtomation.com:8443
Login successful.
You have access to the following projects and can switch between them with 'oc project <projectname>':
ansible-service-broker
* default
Using project "default".
Welcome! See 'oc help' to get started.
PLAY [Deploy ansible-service-broker to  openshift] *****************************
TASK [ansible-service-broker-openshift : oso_service] **************************
changed: [localhost]
TASK [ansible-service-broker-openshift : debug] ********************************
skipping: [localhost]
TASK [ansible-service-broker-openshift : oso_service] **************************
changed: [localhost]
TASK [ansible-service-broker-openshift : debug] ********************************
skipping: …
```
=> Fixes file and directory permission issues in asb container

pkg/apb/types.go, pkg/app/app.go, pkg/broker/broker.go, pkg/broker/provision_job.go, pkg/broker/provision_subscriber.go, pkg/handler/handler_test.go
Instead of creating a new subscriber for EVERY provision, we need to create just one that processes the messages.
=> only create one work subscriber, not per provision

pkg/apb/types.go, pkg/broker/broker.go
fixing issue #99 
* Removing debug of Parameters
* Reducing the deep equals calls
* Adding helper method to check if service instance's are equal
=> Removing duplicate calls to reflect.DeepEquals in broker

pkg/dao/dao.go
Fix for issue #63 
* Also fixing golint things like comments on export methods and structs
=> Removing redundancy in dao for issue #63

Makefile
Added the `-s -w` ldflags to the build step. This reduced the broker binary size from 27M to 15M.
Old build command: `go install -ldflags="-s -w" ./cmd/broker`
```
-rwxrwxr-x. 1 jesusr jesusr 27704824 May 11 19:32 /home/jesusr/dev/bin/broker
```
New build commands `go install -ldflags="-s -w" ./cmd/broker`
```
-rwxrwxr-x. 1 jesusr jesusr 15619712 May 12 13:01 /home/jesusr/dev/bin/broker
```
=> reduce the binary with the -s, -w ldflags

glide.yaml
Add the appropriate pks to glide.yaml so that the vendors
directory can be properly flattened when running `glide install -v`.
Flattening the vendor directory removes duplicate pkgs that will
conflict with pkgs used by the broker.
Partially fixes #100
=> Flatten glide dependencies

pkg/apb/dev_registry.go, pkg/apb/dockerhub_registry.go, pkg/apb/mock_registry.go, pkg/apb/registry.go, pkg/apb/rhcc_registry.go, pkg/broker/broker.go, pkg/broker/types.go, pkg/handler/handler_test.go, scripts/asbcli/asbcli
* When specs fail, print out the error to the log.
* Only include correctly created specs in the completed list.
=> adding ability to continue bootstraping when a spec fails

glide.lock, glide.yaml, pkg/apb/client.go, pkg/app/app.go
Create the Kubernetes client object and use the client to do the cluster validation check by connecting to a running Kubernetes cluster.
Partially fixes #103 
For a complete fix, we need to create an internalclient.
=> Kubernetes client object

pkg/apb/client.go
Always pull the latest image from the registry.
=> Apb pull policy

Makefile, README.md, ansible/main.yml, cmd/broker/main.go, cmd/mock-registry/mock_registry.go, docs/README.md, docs/apb_integration.md, extras/ansible-service-broker.spec, glide.yaml, pkg/apb/bind_test.go, pkg/apb/deprovision.go, pkg/apb/ext_creds_test.go, pkg/apb/types_test.go, pkg/app/app.go, pkg/app/config.go, pkg/broker/broker.go, pkg/broker/broker_test.go, pkg/broker/provision_job.go, pkg/broker/provision_subscriber.go, pkg/broker/types.go, pkg/broker/util.go, pkg/broker/util_test.go, pkg/dao/dao.go, pkg/handler/handler.go, pkg/handler/handler_test.go, pkg/handler/io.go, pkg/handler/io_test.go, scripts/travis.sh
rename the packages and code references to openshift. fusortest will remain fusortest. there are some other references to fusor in apb names, etc which I left alone.
=> Rename fusor to openshift

pkg/apb/client.go
The interface Core() will be deprecated in favor of
CoreV1().
=> Non version interface will be deprecated

Makefile, ansible-service-broker-all.yaml, build/Dockerfile, templates/broker-deployment_template.yaml
This change allows the following workflow to work:
```
make clean # remove broker from build now
make build PROJECT=YOUR_DOCKER_HUB_ORG
docker push docker.io/YOUR_DOCKER_HUB_ORG/ansible-service-broker-apb:latest
make deploy # deploys to local oc cluster
```
This workflow uses the settings found in `etc/dev.config.yaml`.
=> Fix build deploy

README.md
PR #121  removed the get_images_from_org scripts which used
jq.
=> Remove jq since PR#121 merged

pkg/broker/broker.go
Fixing bug #147
* Allowing service instance's to be bindable if they are created without parameters.
=> fixing bug where we attempt to deference nil parameters.

etc/ex.dev.config.yaml, pkg/app/app.go, pkg/app/config.go, pkg/broker/broker.go, pkg/handler/handler.go, pkg/handler/handler_test.go
Adding ability for local APB developers to push their own specs to the Broker to be included in the catalog
Added config value ```devbroker: true``` to turn this on. If that value does not exist in the config it will keep this endpoint off. 
This is needed for https://github.com/fusor/ansible-playbook-bundle/pull/47
=> Add Endpoint for ABP Tool to push Specs

test/bind.sh, test/bootstrap.sh, test/catalog.sh, test/deprovision.sh, test/last_operation.sh, test/provision-200.sh, test/provision-409.sh, test/provision.sh, test/unbind.sh
cap.example.com is dead, and 90% of the use cases are with a broker
running at localhost.
=> change all scripts to use localhost.

templates/deploy-ansible-service-broker.template.yaml, templates/run_template.sh
This adds an OpenShift template which shows how to parameterize options.
The run_template.sh is an example of how to deploy the template with parameters.
Currently this is for information purposes.
Next step will be to update catasb to begin using this file opposed to the "all in one" yaml we have in the project root.
=> Added an OpenShift template for deploying broker & etcd

ansible-service-broker-all.yaml, templates/etcd-deployment.yaml
Verified that data persists after destroying the pod and allowing the deployment to recreate it.
=> create persistent volume claim for etcd data

ansible-service-broker-all.yaml
admin is not sufficient for the broker, service account creation for the apbs was being rejected.
=> Elevate broker service account role to cluster-admin

build/config.yaml, etc/ex.dockerimg.config.yaml, etc/ex.mock.config.yaml, etc/ex.prod.config.yaml, pkg/apb/bind.go, pkg/apb/client.go, pkg/apb/deprovision.go, pkg/apb/ext_creds.go, pkg/apb/hack.go, pkg/apb/provision.go, pkg/apb/svc_acct.go, pkg/apb/types.go, pkg/broker/broker.go, pkg/broker/provision_job.go
Sandboxes apb with dynamically created ServiceAccounts and RoleBindings.
I'm not very happy with the way DestroyApbSandbox works here. We need to revisit it since authors working in the broker.go should should *not* have to worry about leaking the sandboxes; they should always be cleaned up on the conclusion of the pods. I'd personally like to see this get implemented as an event handler that executes on some kind of a pod terminate trigger, but I'm unable to get that in by tomorrow. I plan on following this up with an issue to revisit post TP1.
=> Sandboxed APB Implementation

pkg/apb/bind.go, pkg/apb/client.go, pkg/apb/deprovision.go, pkg/apb/provision.go, pkg/dao/dao.go
The broker logs the user, cluster address, and password to
stdout.  Don't log the password.
=> Cleanup some logging and do not log passwords anymore

pkg/apb/client.go
oc login is sending the parameters used for oc login to std out.
=> Remove the output of params used for oc login

Makefile, docs/local_development.md, etc/.gitignore, pkg/broker/broker.go, scripts/.gitignore, scripts/my_local_dev_vars.example, scripts/prep_local_devel_env.sh, scripts/run_local.sh, scripts/test_local_server_connection.sh, templates/deploy-local-dev-changes.yaml
Assumes running oc cluster up on localhost.
Allows running broker local on host with:
- service account credentials
- etcd route
- modifies asb route to point to local broker
With this PR we can do the following:
1) Use catasb 'dev' branch to bring up a cluster
2) make build
3) cd scripts && ./run_local.sh
The local broker now replaces the broker the Service Catalog was talking to.
I've had success with this doing provision/bind with mediawiki & rhscl postgres example.
Note the broker will not have access to the service network, for example it couldn't reach the running etcd so we created a route to expose it.  We are not talking to the service network for anything else currently, in future this may be a limitation for us.
Also...I've tested this with building broker on macOS and running …
=> Local Development Changes:  Simulates broker running InCluster while executing locally

.tito/packages/.readme, .tito/releasers.conf, .tito/tito.props, ansible-service-broker.spec, docs/building.md, extras/ansible-service-broker.spec
Tito will allow us to build to copr, brew and locally in a consistent manner. We can also use the `tito tag` feature to create tags for the repo. Tito will also update the changelog so we can keep track of what went into the RPM. The same build can be submitted to all of the build systems.
=> Prepare repo for use with tito

pkg/apb/dockerhub_registry.go, pkg/apb/rhcc_registry.go, pkg/apb/types.go, pkg/apb/types_test.go, pkg/broker/util_test.go
Really want to open a discussion on this one. 
I think that it does not make sense to wrap package calls like this unless you are doing more logic for every time you call that method. 
If we do want to continue, then we should update the function 
```
func LoadYAML(yaml []byte, obj interface{}) {
return yaml.Unmarshal(yaml, obj)
}
```
=> removing unnecessary function that just add's indirection.

pkg/apb/client.go
The RefreshLoginToken function is only used with a local
broker. Let's remove this extra code path and have developers
refresh their login token manually when necessary.
Partially-fixes #196
=> Remove refresh login function

pkg/apb/client.go, pkg/app/app.go, pkg/app/config.go, pkg/clients/clients.go, pkg/clients/docker.go, pkg/clients/etcd.go, pkg/clients/kubernetes.go, pkg/clients/types.go, pkg/dao/dao.go
Refactor the broker clients into their own package.
Right now, we have clients scattered around in different packages. This is causing the clients to be initialized on each action (bind, unbind, etc...) as well as other places because the clients aren't available for use.
Let's initialize the clients one time and distribute those clients to the places that need it.  This patch set creates a global struct 'Clients' that gets initialized by app.go before the broker object is created.  Any function that runs after the broker object creation, will have access to all the clients.
Fixes: #213
=> Breakup all the Broker Clients into a clients pkg

Makefile
* make build is now the default target
* make build will only recompile if there were source changes
* make run will rebuild if needed and run prep script if there are no kube cert and token
=> Makefile technical debt

build/automated-build
The docker registry has ability to automatically build containers.
But, the container expects the latest source. We'll use automated-build
to represent the automated build Dockerfile.
Tested this change out here: https://hub.docker.com/r/rthallisey/ansible-service-broker-test-builds/builds/
=> Automated builds from Dockerhub

pkg/broker/provision_job.go
When we provision an APB, we create it and extract
the credentials from it. We don't want to make an explicit
call to extract credentials after a provision because the
expectation is that we already have the credentials.
=> Only Extract the Credentials once

etc/example-config.yaml, pkg/apb/executor.go, scripts/my_local_dev_vars.example, scripts/prep_local_devel_env.sh
The pull policy of an APB should be set by the broker.
To configure it, set image_pull_policy in the config file.
The image_pull_policy setting will be verified that it's
a correct setting. The option is not case sensetive and will
error if an incorrect setting is used.
Fixes https://github.com/openshift/ansible-service-broker/issues/235
=> Make the ImagePullPolicy Configurable

pkg/app/app.go, pkg/clients/clients.go, pkg/clients/etcd.go, pkg/dao/dao.go
The GetEtcdVersion function was a temporary workaround to contact Etcd until we moved to a newer etcd. The change we needed merged in v3.1.1.
=> With a newer Etcd, we can use the GetVersion function

templates/deploy-ansible-service-broker.template.yaml
IMAGE_PULL_POLICY is missing from the deployment template. If a broker is deployed without this in the template, the broker in master is broken (since it derives the pull policy from the cluster config, which will always be "").
=> Add IMAGE_PULL_POLICY to broker template

etc/example-config.yaml, pkg/apb/executor.go, pkg/apb/hack.go, pkg/apb/types.go, pkg/app/config.go, pkg/broker/broker.go, pkg/broker/broker_test.go, scripts/my_local_dev_vars.example, scripts/prep_local_devel_env.sh, templates/deploy-ansible-service-broker.template.yaml
Allows for configuration to tell the broker where to find the cluster host, CAFile, and BearerTokenFile. Good example for how to retrieve these manually can be found in the `prep_local_devel_env.sh`.
1) Run catasb local once, creates prereqs for `prep_local_devel_env.sh`.
2) Run `prep_local_devel_env.sh`, should export CAFile and token files to `/var/run/secrets/kubernetes.io/serviceaccount`.
3) Edit generated configuration file in $YOUR_CHECKOUT/etc/generated_local_development.yaml. Make sure host is your openshift host (https://172.17.0.1:8443 for me) and ca_file/bearer_token_file both point to exported files from the prep script.
4) Run `./broker -c ./etc/generated_local_development.yaml`
5) **Confirm in broker logs successful, secure login**
6) Shut down broker. Set ca_file field to …
=> Configurable, external broker auth support

Makefile, scripts/my_local_dev_vars.example, scripts/prep_local_devel_env.sh, scripts/run_local.sh
The prep_local_devel_env.sh and run_local.sh scripts would only run from inside scripts directory. You can now run them from the project root: `./scripts/run_local.sh`.
=> technical debt: make scripts run from anywhere

pkg/app/app.go, pkg/app/args.go
We are printing error messages and the help menu
twice. Also, clean up some unused options.
Closes-bz1469401
=> 1469401 - Print out error messages only once

pkg/app/app.go, pkg/app/args.go
We are printing error messages and the help menu
twice. Also, clean up some unused options
Cherry-pick  #264 from release-0.9
=> Only print out error messages only once

pkg/apb/bind.go, pkg/apb/deprovision.go, pkg/apb/ext_creds.go, pkg/apb/provision.go, pkg/apb/types.go, pkg/broker/broker.go
Change the broker bind output from trailing the logs of
the provision or bind container to exec'ing into the container.
=> Broker bind output rework

pkg/apb/provision.go
If the project does not exist, broker will report and return error
=> 1470860 - Remove broker project creation 

pkg/apb/ext_creds.go
This log is expected to repeat a bunch under normal circumstances and marking it as a warning suggests something is out of the ordinary.
=> Downgrade ext_cred retry logs to Info

pkg/apb/bind_test.go, pkg/apb/ext_creds.go, pkg/apb/ext_creds_test.go, pkg/apb/types.go
We can predict the error code returned from RunCommand and use
it to gather bind credentials.
depends-on: https://github.com/fusor/apb-examples/issues/34
=> Improve the broker bind output by using error returned from RunCommand

pkg/apb/types.go
Longer running apps need a longer timeout. This timeout isn't just
for bind. It's the timeout of an apb so it needs to be higher.
=> Increase bind timeout to 30minutes

ansible-service-broker.spec
This does not evaluate properly, besides which selinux-policy is a dependency of selinux-policy-targeted, which is already a requires.
=> Remove bogus selinux requires in rpm spec

.travis.yml
Add the -c asb flag to the .travis oc logs commands so we get
the logs from the broker on a failure.
=> The broker now has two containers in a single pod - fix travis

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
The PR and Issues template will help guide a developer when
create a new PR or issue. This will help organize the git repo
so the community can review PRs and fix bugs  faster.
=> Add a PR and Issues template

scripts/prep_local_devel_env.sh
I had an oversight when I reviewed PR 305. The change from using jq to jsonpath also introduced this bug where we stopped looking at the tls.crt which is actually quite important
=> get both tls.key AND tls.crt not two tls.keys

pkg/fusortest/util.go
Will determine the actual file that caused the issues and print that out during the test run.
Allows user's to more easily see the tests that were broken. and example out put is
```
--- FAIL: TestRegistryLoadSpecsNoError (0.00s)
util.go:113:
registry_test.go had error on line 165
Message: 1 != 2
```
- get the actual caller of the fusor test method
- 3 callers up, 0 -> call to Callers, 1 -> call to unexported ```fail``` 2 -> call to  unexported ```assert```, 3 -> call to the public ```AssertXXXX``` method.
No
fixes #320
=> fusor test will now print out details on the actual file

pkg/handler/handler.go
Move to a common way of retrieving data from query parameters.
- remove uses of r.URL.Query() and the resulting value
- use [request.FormValue](https://golang.org/pkg/net/http/#Request.FormValue)
No 
fixes #303
=> updating handler to use FormValue call to retrieve data from query param

build/Dockerfile, etc/example-config.yaml, pkg/app/config.go, pkg/app/config_test.go, pkg/app/testdata/test-config.yaml, pkg/auth/auth.go, pkg/auth/auth_test.go, pkg/auth/basic_auth.go, pkg/auth/basic_auth_test.go, pkg/broker/broker.go, pkg/handler/handler.go, pkg/handler/handler_test.go, scripts/broker-ci/broker-resource.yaml, scripts/my_local_dev_vars.example, templates/deploy-ansible-service-broker.template.yaml
Currently supports just basic auth but it's structured to allow extension for additional auth backends.
=> Introduce authentication to the broker

docs/config.md, pkg/apb/unbind.go, pkg/broker/broker.go, pkg/handler/handler.go, scripts/prep_local_devel_env.sh
Implementation for #293. Just getting thoughts down. This allows you test with the the test apps and APB  
https://github.com/shawn-hurley/rhscl-postgresql-apb
https://github.com/shawn-hurley/bottle-todo-demo
=> Adding ability to pass credentials to bind and unbind actions.

scripts/broker-ci/error.sh, scripts/broker-ci/local-ci.sh, scripts/broker-ci/logs.sh
Print the error summary last.
- Improves CI logging
- Fixes an error with duplicate PROVISION_ERROR checks
- Print CI run output last
- Close file descriptors after we're done with them
=> Improve CI logging

pkg/registries/adapters/dockerhub_adapter.go, pkg/registries/adapters/dockerhub_adapter_test.go, scripts/run_latest_build.sh
The main purpose of this PR is to go through the process and be
introduced to it.
- Dockerhub adapter now handles err on failure to generate token
- scripts/run_latest_build.sh now uses the docker user, pass, and
organization information
- A test for the dockerhub_adapter now exists, albeit a trivial one
=> Handle err when generating Dockerhub token

scripts/prep_local_devel_env.sh
Prevents failures from prep_local script when not explicitly in the ansible-service-broker project
=> Explicitly use project name for ASB secrets

docs/specs/add-kubernetes-support.md
Spec outlining the work for supporting Kubernetes.
https://github.com/openshift/ansible-service-broker/issues/233
=> Spec: Kubernetes and COE agnostic support

scripts/prep_local_devel_env.sh, templates/deploy-local-dev-changes.yaml
The default route created by catasb uses reencrypt. Reencrpt will
only work with tls connections.
- Allow the local broker to work in insecure mode
=> Allow the local broker to run in insecure mode

build/entrypoint.sh, templates/deploy-ansible-service-broker.template.yaml
Running the broker in insecure mode from the template should
only require changing a few settings.
- Option to run the broker as insecure from the openshift template
fixes https://github.com/openshift/ansible-service-broker/issues/333
=> Add an insecure option to the openshift template

scripts/prep_local_devel_env.sh
* Need to make sure we're using the same registry name as was used when
catasb was original brought up so that matching IDs are generated.
"dockerhub" vs "dh" will produce different IDs when hashed, manifesting
as 400s on provision requests (/spec lookups will miss)
- Update registry name to match shortened name in main deployment template
fixes #352
=> Match template registry name

scripts/my_local_dev_vars.example, scripts/prep_local_devel_env.sh
Most broker developers don't use the in cluster etcd instance and instead prefer an instance running locally so etcdctl and other tools can be used to interact with raw etcd. This PR introduces a proper configuration param so we can stop hacking up the generated config.
- Set LOCAL_ETCD="true" in `my_local_dev_vars` to have `prep_local` script configure for a local etcd instance running on the developer's host.
=> Add local etcd support for local env

scripts/run_latest_build.sh
- Add basic auth switch to run_latest_build.sh
- Default to basic auth turned off for dev deployments based on run_latest_build.sh
=> Add basic auth switch (default off) to run_latest_build.sh

.travis.yml, Makefile, scripts/travis.sh
The purpose of this update is to start bringing some of the automation
for CI into one place. In the current state, I test locally through
several executions of the travis shell script. What I propose as an
alternative is to bring in as much of that shell script into a Makefile
as possible.
The intention is to make it so a contributor can simply run `make ci` to
run a local version of what travis will accomplish when a PR is
created and add a help target that prints helpful imformation.
- Removed all but the install portion of travis.sh and made that a
function to be called
- Simplified the Makefile and travis.yaml
=> Update broker makefile

.gitignore, pkg/apb/deprovision.go, pkg/apb/ext_creds.go, pkg/apb/types.go, pkg/apb/watch_pod.go, pkg/app/app.go, pkg/broker/broker.go, pkg/broker/deprovision_job.go, pkg/broker/deprovision_subscriber.go, pkg/broker/provision_job.go, pkg/broker/provision_subscriber.go, pkg/broker/types.go, pkg/broker/work_engine.go
* Added topics to work engine
* Added deprovision subscriber, make sure the ProvisionSubscriber stops
processing deprovision messages as previously written
* Added pod watcher for actions that don't require cred extraction
but still need to watch for completion and handle
* Various refactoring to leverage new stuff
fixes #341
=> Work Topics and Deprovision Fixes

scripts/travis.sh
I wanted to duplicate ```if ! ${ERROR};``` logic where we only run
```make ci``` if the setup worked.. Instead, ```make ci```
only runs when the setup errors.
- Fixes a false positive introduced from #348
=> Fix rebase mistake

pkg/broker/broker.go, pkg/registries/adapters/adapter.go, pkg/registries/adapters/dockerhub_adapter.go, pkg/registries/adapters/openshift_adapter.go, pkg/registries/adapters/rhcc_adapter.go, pkg/registries/registry.go, scripts/broker-ci/mediawiki123.yaml, scripts/broker-ci/postgresql.yaml, templates/deploy-ansible-service-broker.template.yaml
Specify alternate tags for APB's. In order to more easily test canary/nightly apb images.
- Add a 'tag' config option for registries in the config.yaml. The template will default it to latest.
There's a half way done PR for catasb that will make it easier to override the tag.
N/A
=> Allow specifying a tag for apbs

CONTRIBUTING.md, Makefile, docs/deployment.md, scripts/run_latest_build.sh, templates/deploy-ansible-service-broker.template.yaml
Make it so the broker template and project documentation refer to the `origin-ansible-service-broker` docker image.
=> Use origin-ansible-service-broker docker image

docs/auth.md, docs/proposals/bearer-token.md
Add bearer token auth to the service broker.
=> bearer token proposal

pkg/apb/ext_creds.go, pkg/apb/provision.go, pkg/apb/svc_acct.go, pkg/apb/watch_pod.go, pkg/broker/broker.go, pkg/runtime/hack.go
Create the runtime pkg and start converting a few things to using ```kubectl```.
Remaining Commands:
- ```oc login```
- creating svc accounts
- creating rolebindings
- Move RunCommand to the runtime pkg 
- Use ```kubectl``` for a few commands
=> Move the client calls to the runtime pkg

pkg/apb/executor.go
Adds some additional identifying metadata in the form of a label to help users identify what services apb pods are deploying.
=> Label APBs with their FQNames

Makefile, build/Dockerfile-canary, build/Dockerfile-localdev, build/README.md
automated-build is what is currently being used to build Canary images. As such I'm renaming it to conform with the scheme I brought up @ Wednesdays meeting. To do this I need to call the Dockerfile being used by the Makefile something else. I chose -localdev for lack of any better idea.
- Move Dockerfile-canary to Dockerfile-localdev
- Move automated-build to Dockerfile-canary
- Fix Makefile to track this change
No
N/A
=> Update Dockerfile names

docs/proposals/updates-first-pass.md
Think this is a decent starting point, there is a lot to this that I think we'll discover as we move through implementation. I'll try to continue to update this document for anything major. IMO we'll probably be iterating on this a bunch.
=> Updates first-pass proposal

Makefile
Adds the build of the broker to the build-image target
- add the broker build step to the build-image target
fixes #394
=> adding broker build to build of image.

pkg/apb/types.go, pkg/broker/util.go, pkg/broker/util_test.go, pkg/broker/work_engine.go, pkg/clients/clients.go, pkg/clients/kubernetes.go, pkg/registries/adapters/openshift_adapter.go
Added UI form information to metadata fields for parsing by OpenShift UI.
https://github.com/openshift/ansible-service-broker/blob/master/docs/proposals/form-metadata.md
- Add json regarding parameter order, groups, and display type to metadata in the json-schema-form definition.
- Unit tests
=> Added UI form information to metadata fields for parsing by OpenShift

pkg/apb/types.go, templates/deploy-ansible-service-broker.template.yaml
- Update `asb` cluster role binding to admin cluster role instead of
cluster-admin.
- Update the apb sandbox cluster role that we target for the namespaced
role binding to be edit instead of cluster-admin.
=> [WIP] Reduce broker/apb sandbox permissions

pkg/apb/ext_creds.go, scripts/broker-ci/local-ci.sh
I noticed when running the local-ci script that there were spelling
mistakes in both the local-ci script and the logs being dumped for the
broker. As going through all files would be a long process, this change
addresses all the issues found in the two files I noticed had issues
from the logs.
N/A
N/A
=> Fix spelling in logs

pkg/broker/util.go, pkg/broker/util_test.go
While making fixes in previous PR, I accidentally misnamed a variable and was duplicating the last parameter when creating a form definition.  That is fixed and a test case added.
=> Fixed duplicate parameter after group.

scripts/broker-ci/apb.yml, scripts/broker-ci/error.sh, scripts/broker-ci/local-ci.sh
Add unbind and deprovision checks. Well, rhsck-postgresql deprovision was busted when I started testing, so it seems like a good idea.
- Check to ensure unbind works
- Check to ensure deprovision works
N/A
N/A
=> CI: add unbind and deprovision checks

pkg/broker/broker.go, pkg/broker/broker_test.go
Will see if the FQname was cut off at a "-" character
fixes #377
=> 377 - The service name returned by asb is invalid

.gitignore
The ag search tool respects the .gitignore file but having broker alone
was too aggressive for the tool. So by adding the / it tells git to
ignore broker only at the project root.
=> ignore the broker only at the root

ansible-service-broker.spec
Changes the build command in the RPM spec. We have been getting an error due to using -tags, but it has not been fatal until Fedora 27.
- On the related bug the suggestion if using any other flag besides -o is to use the go build command directly rather than %gobuild, so I am doing that.
- https://bugzilla.redhat.com/show_bug.cgi?id=1409931
N/A
N/A
=> Update build to also work with Fedora 27

scripts/run_latest_build.sh
Based on discussion in the #asbroker, it seemed possible that moving the
variable assignments to just before the `oc process` would make it
easier to see our recommended values.
=> Move variable assignment for clarity in script

scripts/broker-ci/local-ci.sh
Sometimes the mediawiki pod complains about a secrent not being
mounted from the service account APB. I'm not sure why yet,
but this will at least be a work around for now.
=> Force delete the mediawiki pod

docs/auth.md, templates/deploy-ansible-service-broker.template.yaml
In order to work with newer service-catalogs we need a way to specify in the template the Kind and Auth for the broker.
We can do this for instance with catasb by adding to the template processing:
```
- name: Update Broker Kind and Auth when using coalmine
set_fact:
cmd_process_asb_template: >-
{{ cmd_process_asb_template }}
-p BROKER_KIND="ServiceBroker"
-p BROKER_AUTH='{ "basic": { "secretRef": { "namespace": "ansible-service-broker", "name": "asb-auth-secret" } } }'
when: coalmine is defined and coalmine
```
- Add support to specify BROKER_KIND and BROKER_AUTH in the openshift template
- Set defaults for current service-catalog images in dockerhub openshift repos
**Does this PR depend on another …
=> Update template to support newer service-catalogs

docs/config.md, docs/filtering_apbs.md, etc/example-config.yaml, pkg/registries/filter.go, scripts/prep_local_devel_env.sh, templates/deploy-ansible-service-broker.template.yaml
The goal of the PR is to make the default behavior for the time when there is no white list or black list to be the most restrictive, and not include any APBs.
- Default for `NoFilterMode` is to not include any APBs
- Template updates to make catasb behave as it does today. 
- Updates to the `prepare_local_devel_env.sh` so that it will behave as it does today.
=> Default for no filter mode is to not contain a single APB.

README.md
Fixes location of IRC links to go to our channel and not openshift-dev
=> updating irc links to go to asbroker channel

scripts/run_latest_build.sh
thomasmckay in irc was trying to run the latest service broker with a 3.7 server. The template uses `Broker` kind by default instead of the required `ServiceBroker`. Defaulting to `Broker` so that it works with 3.6 and folks can override it:
```
BROKER_KIND="ServiceBroker" ./scripts/run_latest_build.sh
```
=> pass in BROKER_KIND

templates/deploy-ansible-service-broker.template.yaml
Update the ansible-service-broker template to work with service-catalog 0.0.17 by default since it is now the default in origin:latest
- Update BROKER_KIND and BROKER_AUTH
Merge with: https://github.com/fusor/catasb/pull/139
fixes N/A
=> Update broker defaults for current service-catalog version

scripts/run_latest_build.sh
There are some changes between 3.6 and 3.7 happening and the run_latest_build script was missing a template param.
=> The run_latest_build script is missing an auth param

pkg/registries/adapters/dockerhub_adapter.go, scripts/broker-ci/setup.sh
Fixes issue 448 
- Set basic auth on retrieval of the bearer token for the registry service.
fixes 448
=> allowing the user to authenticate to retrieve private repos

pkg/broker/util.go, pkg/broker/util_test.go
Currently, broker is listing all parameters intended for provision as binding parameters when creating a binding.  Until binding parameters in the broker is implemented, we need to remove these parameters as they are not currently used and add confusion to the user experience.
Removes the service_binding.create paramaters and openshift_form_definition from the catalog request.
=> Remove provision parameters from being reused as binding parameters.

scripts/asbcli/asbcli
It fixes asbcli. We need it because this should have been done before Bearer Auth was merged.
- Use SSL (unverified)
- Retrieve and send the user token in headers
depends-on
N/A
fixes
N/A
=> fix asbcli to work with bearer auth

.tito/tito.props, pkg/app/app.go, pkg/registries/adapters/adapter.go, pkg/registries/adapters/adapter_test.go, pkg/version/apbversion.go, pkg/version/version.go, templates/version.go.tmpl
This PR adds version checks to the broker when bootstrapping an APB
- Move version.go to its own version pkg
- Add version check on imageToSpec conversion
- Add unit tests for compatible version checks
Note:
I plan to open an issue to move the version to the spec itself so that this check moves out of the adapter pkg.
=> Added versioning check to Broker on bootstrap

scripts/run_latest_build.sh
Fixing run latest to start with the correct defautl after the bearer token auth merge.
This should have been apart of that PR.
- Change default for basic auth to true for the broker.
N/A
N/A
=> changing default for 3.6 run_latest_build to function correctly

scripts/broker-ci/local-ci.sh
The bind is being created before the postgresql pod returns the
bind credentials causing a failure.  Increase that wait time from
10 to 30 seconds.
Add a wait_for_resource for the bind secret to exist before looking
for pod presets in mediawiki.
- wait 10s increase to 30
- wait for podpreset secret
=> Bump wait times

scripts/deploy.sh, scripts/kubernetes/deploy.sh, scripts/openshift/deploy.sh
These two scripts are very different because one will use OpenShift
templates and the other will use jinja2. I added an intermediate script
that will direct to the proper location.
- Run ```make deploy``` for both openshift and kubernetes envs
=> Split the deploy.sh script to work with both kube & openshift

docs/auth.md, docs/config.md, docs/deployment.md, docs/ssl_tls.md
Follow on PR for #445 for the documentation
- Update the auth documentation to document both how to set up auth, and how it is implemented.
- Update various other docs to include updates.
N/A
N/A
=> Bearer auth documentation

scripts/run_latest_build.sh
Provide an environment variable to deploy latest with run_latest_build
- introduces a ORIGIN_VERSION env variable, which default to v3.6.0
-
-
=> Provide an environment variable to deploy latest with run_latest_build

.tito/releasers.conf
Had to add the 3.7 brew releaser so we can build against the 3.7 buildroot.
=> add 3.7 releaser to releasers.conf

pkg/broker/provision_subscriber.go
Overwrites the extracted credentials and provision message for each return on the msg buffer channel.
- Overwrites the extracted credentials and provision message for each return on the msg buffer channel.
=> Bug 1498203 - Extracted Credentials were leaking into new bindings

pkg/apb/types.go, pkg/broker/broker.go, pkg/broker/broker_test.go, pkg/registries/adapters/adapter.go, pkg/registries/adapters/dockerhub_adapter.go, pkg/registries/adapters/openshift_adapter.go, pkg/registries/adapters/rhcc_adapter.go, scripts/broker-ci/mediawiki123.yaml, scripts/broker-ci/postgresql.yaml
The purpose of this change is to make it so that the full path to each
image is used when executing APBs instead of relying on what is stated
in the APB yaml.
- Update the Spec to make Image optional (for when we remove it from APB
yaml)
- Update the registry adapters to store the full path to the image when
unmarshalling the APB yaml -> APB spec before we store it into `etcd`
- Update the broker to have simpler format for `FQName`
Implements #431
Fixes #288
Bug 1497819
=> 1497819 - Broker should not rely on image field of APB yaml

pkg/apb/types.go, pkg/apb/types_test.go, pkg/registries/adapters/adapter.go, pkg/registries/adapters/adapter_test.go, pkg/registries/registry.go, pkg/registries/registry_test.go
This PR adjusts for the change of moving the APB spec version from an image label into the Spec itself. It also moves the version check out of the adapter package so that it is now obfuscated out of each individual adapter.
- Move APB spec version check to spec validation in registry package
- Adds unit tests for specs without versions
This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1498185
=> Bug 1498185 - Adjust versioning check so that it is done in the registry package

docs/proposals/keeping-transient-pod-name-spaces-alive.md
Proposal for [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1497766)
=> Creating proposals for keeping transient namespace alive

docs/proposals/bind-parameters.md, pkg/apb/types.go, pkg/broker/broker.go, pkg/broker/util.go, pkg/broker/util_test.go, pkg/fusortest/util.go, scripts/prep_local_devel_env.sh
Support bind parameters. Proposal included.
=> Bug 1498618 - Support bind parameters.

pkg/broker/broker.go
This PR checks the list of bootstrapped specs for apb-push sourced specs before deleting the entire set of APBs. It then saves the apb-pushed specs to a new array, and adds them back in after the bootstrap. We need this because without apb-push sourced specs are being deleted.
- Check for apb-push sourced specs, if they exist save them and append them to spec list after the bootstrap
fixes https://github.com/openshift/ansible-service-broker/issues/391
=>  Bug 1498933 - Do not delete apb-push sourced specs when bootstrapping 

pkg/broker/broker.go
Just used the apb tool to push an image to the broker and looked at how the image was stored by looking at the logs of the broker.
```
[2017-10-05T14:22:55.126Z] [DEBUG] handler::apbAddSpec
[2017-10-05T14:22:55.126Z] [DEBUG] Successfully decoded pushed spec:
[2017-10-05T14:22:55.126Z] [DEBUG] version: 1.0
name: hello-world-apb
description: deploys hello-world web application
bindable: False
async: optional
metadata:
displayName: Hello World (APB)
longDescription: A sample APB which deploys a containerized Hello World web application
dependencies: ['docker.io/ansibleplaybookbundle/hello-world:latest']
providerDisplayName: "Red Hat, Inc."
plans:
- name: default
description: A sample APB which deploys Hello World
free: True
metadata:
displayName: Default
longDescription: This plan deploys a …
```
=> Bug 1498954 - Broker in developer mode must support apb push

docs/README.md, docs/troubleshooting.md
Documentation for troubles users/developers may see.
=> Add troubleshooting documentation to the broker

pkg/apb/types.go, pkg/apb/types_test.go, pkg/broker/broker.go, pkg/broker/broker_test.go, pkg/broker/util.go, pkg/broker/util_test.go, pkg/dao/dao.go
With a recent service-catalog change, the serviceplans were moved to top level. We were using the plan.name as the plan.id which was not a problem before because they were namespaced by the serviceclass.
Now that the serviceplans are top level, the names need to be unique. Since we used to rely on the serviceclass name, the new id will be a UUID. We are now storing the id and name in etcd.
```
/plan_names/UUID: plan.name
```
fixes 1500048
=> Bug 1500048 - make plan ids globally unique

pkg/apb/secrets.go, pkg/broker/broker.go
* Removes hardcoding of the broker's namespace from secrets lookup.
=> Bug 1500934 - Dynamic broker ns for secrets

pkg/broker/broker.go
Responds to duplicate bind requests with the already created credentials in the body.
- create buildBindResponse function to build the bind response.
-
-
fixes 1501512
=> Bug 1501512 - bind issue when multiple calls to create the same binding

pkg/apb/types.go, pkg/broker/broker.go, pkg/broker/deprovision_subscriber.go, pkg/broker/provision_subscriber.go, pkg/dao/dao.go, pkg/dao/filters.go, pkg/handler/handler.go
Returns the correct 202 Accepted response if a deprovision job is already in progress for a requested ServiceInstance DELETE.
=> Bug 1500930 - Prevent multiple deprovision pods from spawning if a job is already in progress

docs/config.md
Just updates the fqname in the example in the docs for associating secrets with apbs.
=> Update secrets docs to account for new fqname.

pkg/registries/adapters/adapter.go
Update error message to deal with unauthorized users to a registry
**Changes proposed in this pull request**
- Add a check for the `Unauthorized` status response
N/A
fixes 1496572
=> Bug 1496572 - Clean up error message for invalid registry credentials.

docs/config.md, docs/deployment.md, etc/example-config.yaml, pkg/apb/bind.go, pkg/apb/deprovision.go, pkg/apb/provision.go, pkg/apb/svc_acct.go, pkg/apb/types.go, pkg/apb/unbind.go, scripts/prep_local_devel_env.sh, templates/deploy-ansible-service-broker.template.yaml
Keep namespace alive based on new configuration values
- Adds new Config options
- will keep namespace if needed 
https://github.com/openshift/ansible-service-broker/pull/464
CATASB PR: https://github.com/fusor/catasb/pull/155
=> Bug 1497766 - Adding ablity to specify keeping namespace alive

scripts/broker-ci/bind-mediawiki-postgresql.yaml, scripts/broker-ci/cleanup-ci.sh, scripts/broker-ci/error.sh, scripts/broker-ci/local-ci.sh, scripts/broker-ci/logs.sh, scripts/broker-ci/mediawiki123.yaml, scripts/broker-ci/postgresql.yaml
Transition the broker script to work with 3.7
- Create the bind secret
- Populate the bindTarget's pod with secret data
- Transition to 3.7 api types
=> Move the gate to 3.7

pkg/apb/executor.go, pkg/apb/svc_acct.go
Removes split code path based on secrets to run the APB in the transient namespace always
- remove branch on secrets 
- copy secrets to the transient namespace
- panic the broker if we are attempting to delete its namespace.
N/A
N/A
Fixes: #385
=> Bug 1497839 - copy secrets to transient namespace and always run

pkg/apb/bind.go, pkg/apb/deprovision.go, pkg/apb/provision.go, pkg/apb/svc_acct.go, pkg/apb/unbind.go, pkg/handler/handler.go
This PR is meant to address a few errors with respect to service catalog requests to provision/deprovision.
1. Return accepted on requests to deprovision when performing async operations
1. Defer sandbox teardown to prevent leaks and allow proper apb failure handling
=> Bug 1502044 - deprovision fixes

pkg/broker/broker.go, pkg/handler/handler.go
This PR fixes the scenario when the catalog sends two provisioning requests and we return a 200 without checking for jobs in progress.
- Check for provisioning jobs and return 202 if jobs are running.
=> Bug 1499622 - Return 202 if provisioning job is in progress

pkg/apb/deprovision.go, pkg/apb/executor.go, pkg/apb/provision.go, pkg/apb/svc_acct.go, pkg/app/app.go, pkg/broker/broker.go, pkg/broker/deprovision_job.go, pkg/broker/deprovision_subscriber.go, pkg/broker/provision_job.go, pkg/broker/provision_subscriber.go, pkg/metrics/metrics.go, pkg/registries/registry.go
Adds Prometheus metrics for the ASB 
- Metrics package to manage the Prometheus metrics 
- Adding new endpoint from `apiserver` `/metrics`
N/A
N/A
=> Adding prometheus metrics for ASB

scripts/create_broker_secret.py
Running the `./scripts/create_broker_secret.py` script will now check the catalog for a FQName that looks like the image passed in. This should make it work with non-dockerhub registries as well as locally pushed images.
- Added dependency on requests library to use the script
- Get a list of apbs from `/v2/catalog`
- Match the provided org, image, and tag to the apbs in the broker
- If multiple match, prompt the user to pick one
depends on https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/pull/143
=> Look at the apbs in the catalog for a matching name when creating a secret

docs/troubleshooting.md
Adding documentation for using the metrics endpoint
**NOTE: does the troubleshooting doc make sense?**
- Add documentation on how to use the prometheus endpoint
=> Adding docs for prometheus.

pkg/broker/broker.go
Simple enhancement so that we can see the state of the last operation when the service-catalog requests it.
=> Bug 1504729 - Log job state when getting last op

templates/deploy-ansible-service-broker.template.yaml
Use the recreate strategy for the broker deployment.
=> Bug 1504957 - Broker should use recreate strategy

pkg/broker/deprovision_subscriber.go
We want the subscriber to keep listening for deprovision messages even if a previous deprovision fails.
See https://bugzilla.redhat.com/show_bug.cgi?id=1504250 for recreation steps.
Before this change 'deprovision complete msg' would be sent to the channel but there would not be a corresponding 'processed deprovision message from buffer'.
After this change (from broker logs):
```
...
[2017-10-19T20:07:53.008Z] [DEBUG] sending deprovision complete msg to channel
[2017-10-19T20:07:53.008Z] [DEBUG] Processed deprovision message from buffer
```
=> Bug 1504250 - Keep listening for deprovision messages

pkg/broker/util.go, pkg/broker/util_test.go, pkg/fusortest/util.go
- Make sure parameter types are specified for update
depends-on N/A
fixes N/A
=> Bug 1506713 - handle updatable enum parameters properly in schema output

pkg/apb/deprovision.go
Skip deprovision if the namespace is being deleted since we can't access it and it's going to be deleted anyway.
=> Bug 1476173 - Skip deprovision if the namespace is being deleted

scripts/broker-ci/logs.sh
The service-catalog namespace was changed to kube-service-catalog in 3.7.
=> Call the correct service-catalog namespace

Makefile
Always build the broker binary for OS of Linux and output to the build directory
fixes #521
=> when building the broker for image always build for linux OS.

pkg/broker/broker.go, pkg/broker/types.go
This PR resolves issue https://github.com/openshift/ansible-service-broker/issues/481
and part of https://github.com/openshift/ansible-service-broker/issues/470
- pass through the serviceClassID and serviceInstanceID to provision and bind apbs
**Note**
Not currently passing through the user as is mentioned in issue 470. Is this still something that is wanted? I can see the user is resolved and could be passed down to the broker methods. 
If we wanted to pass the user would we pass the entire user object or just the username perhaps?
**Testing**
The unit tests for the broker seemed a bit lacking so tested this manually: The apb and asb logs appeared as follows:
Is this sufficient?
```
[[ provision --extra-vars …
```
=> Bug 1508084 - Add ServiceClassID and ServiceInstanceID params during provision and bind

docs/auth.md, pkg/broker/work_engine.go, pkg/broker/work_engine_test.go
during a refactoring of the work engines to support async deprovision
and update we missed the buffer size.
fixes 1502044
=> Bug 1502044 - add buffer size and work_engine test

scripts/prep_local_devel_env.sh, templates/deploy-ansible-service-broker.template.yaml
* Also since we are now using 3.7 moves to using kubernetes rbac.
Changing the default for auto escalate to false. Currently, we are by default testing no authorization code paths, this change will turn on the authorization code paths by default. 
- update apiGroup and kind for rbac resources to use kubernetes and not openshift in the deployment template
- update default value for deployment template parameter `AUTO_ESCALATE` to false
- update default for prep_local_devel_env.sh to false when generating the configuration.
Should be merged with https://github.com/fusor/catasb/pull/168
**Which issue this …
=> Changing the default for auto escalate to false

scripts/prep_local_devel_env.sh
prep local fails sometimes when the asb-token isn't listed first.
=> Smallfix: grep for correct asb-token for local dev.

scripts/prep_local_devel_env.sh
Make sure we turn off autoescalate by default when doing a `make prep-local-env`.
=> Setting generated local dev template to autoescalate: false

pkg/broker/broker.go
Replaces the fix for setting the plan ID for the spec during apb push.
- Sets plan ID in AddSpec
=> Bug 1501523 - Add spec plan to image during apb push

pkg/apb/deprovision.go, pkg/broker/broker.go, pkg/broker/deprovision_job.go, pkg/broker/deprovision_subscriber.go, pkg/handler/handler.go, pkg/handler/handler_test.go
Redo deprovision of apbs in terminating namespaces to work when autoescalate is false.  Skip user permission verification if the namespace is being deleted and clean up our etcd without running deprovision.
=> Bug 1476173 - Cleanup deleting namespaces

pkg/registries/adapters/rhcc_adapter.go
If we look at Host in the url go pkg without http, the Host
will show up empty.  Instead, URL has a String() function that
will give us the url we need. It returns: 'String reassembles
the URL into a valid URL string'.
=> Bug 1508724 - Look for the url in the proper place

pkg/clients/openshift.go, pkg/registries/adapters/adapter.go, pkg/registries/adapters/local_openshift_adapter.go, pkg/registries/adapters/local_openshift_adapter_test.go, pkg/registries/registry.go, templates/deploy-ansible-service-broker.template.yaml
This PR addresses Bug 1507111 to add an adapter for the internal OpenShift registry.
- New adapter file
- New clusterrolebindings for asb service account to access imagestream resource
- More openshift client changes so that we can access the imagestream resource
=> Bug 1507111 - Add support for a local OpenShift Registry adapter

pkg/apb/ext_creds.go
We were ignoring an error when an apb failed during provisioning and
marking the apb as completed. This resulted in failed apbs looking as
though they provisioned fine.
Fixes #506 - apb provisioning sets ServiceInstance as successful when apb fails
Fixes Bug 1504927 -  ASB Failed provision marked successful even on pod error
Fixes Bug 1470851 - Image Pull Error is being marked as Success
=> Bug 1504927 - if apbs fail, mark them as failed.

pkg/registries/adapters/rhcc_adapter.go
`.String()` will add the scheme to the URL. We will need to ignore that, therefore if the Host value is not set, the Path vale will be set. 
example: 
https://play.golang.org/p/5UrBpwtNeA
fixes bz#1508724
=> Bug 1508724 - Fixing RHCC registry name

pkg/registries/adapters/adapter.go
If you set an incorrect tag for your images in the broker config, the logging
does not indicate what the error is.  Instead, make a suggestion
about the error and print out the request body.
- Improve logging when an incorrect tag is used
=> Bug 1508724 - Improve logging when using an incorrect tag

pkg/registries/adapters/local_openshift_adapter.go
This PR changes default behavior of local registry adapter to not error out if APB name does not start with IP+port. This was erroring out when a user's image was being tagged with the svc name instead.
- Change error to debug statement and continue
- Set default namespace to `openshift` if not set
=> Bug 1507111 - Do not force image tag to be IP + Port

scripts/release_notes.sh
First iteration on the idea of automatically generating release notes
emails that we may or may not want to send out.
Example usage:
```
./scripts/release_notes.sh ansible-service-broker-1.0.5-1
```
=> Create release notes script to grab changes

.gitignore, Makefile, README.md, scripts/travis.sh
- integrating travis-ci with goveralls (coveralls for golang)
- generate coverage reports of our code to better understand our testing
- also added a target for developers to see the coverage locally: `make ci-test-coverage`
none
none
=> Integrate with coveralls for code coverage

pkg/apb/executor.go
Use kubernetes downward API to expose the pod name and namespace to the
APB. This will give us more flexibility w.r.t. managing APB execution,
secrets, and annotations.
=> Expose the pod name/namespace to APB

docs/proposals/prop-apb-gen-creds.md
A proposal to remove (really deprecate) `kubectl exec` from bind
credential extraction process.
=> Proposal to improve bind credential extraction

scripts/kubernetes/resources.sh, scripts/prep_local_devel_env.sh, templates/k8s-ansible-service-broker.yaml.j2, templates/k8s-local-dev-changes.yaml, templates/k8s-variables.yaml
Change kubernetes template use bearer token auth.
- Fixes kubernetes broker setup since bearer auth merged
depends-on: https://github.com/fusor/catasb/pull/164
=> Setup tls support for k8s deployments

pkg/broker/util_test.go
Using a table driven test case similar to what @maleck13 has proposed. This is using an existing test to see how it compares.
=> using table driven testing

pkg/apb/provision_or_update.go, pkg/apb/svc_acct.go
Verify that a namespace exists using the kubernetes API.
- Fixes issue in k8s where projects don't exist
=> Use the Kubernetes API for namespaces check

Makefile
Update a comment in the Makefile.
The non-suffixed repo is redundant and I want to remove it. Keeping it up to date doubles the number of builds we're doing and copr is already under a crushing load so we're not helping them or us to enjoy a stable service.
=> Update copr link in Makefile comments

config.yaml
The new ci framework uses the git repos of APBs to carry templates
that will operate the APBs.  This patch will point CI at the templates
in the APB's git repos.
Also, keep the existing templates in tree for cli testing.
- Point CI to the APB's git repos
=> Pull apb templates from their respective git repos

docs/proposals/last-operation-description.md
Proposal to allow APBs to write a last operation description and have the broker collect and return it as part of the last_operation API
https://github.com/openshift/ansible-service-broker/issues/475
**Note**
While I am becoming more familiar with the broker code, I am still very new to the code base so would appreciate an feedback on the approach outlined here.
On the APB side I would need to investigate the code in order to better understand how we could add a module to allow writing to the log file.
=> First pass at last_operation description proposal

pkg/apb/executor.go, pkg/apb/provision_or_update.go, pkg/apb/secrets.go, pkg/apb/svc_acct.go, pkg/app/app.go, pkg/app/config.go, pkg/clients/clients.go, pkg/clients/kubernetes.go, pkg/handler/handler.go, pkg/registries/adapters/local_openshift_adapter.go
In the Clients pkg, each of the clients should have a Class to
reference.  This creates the Kubernetes class reference so we
can build specific Kubernetes functions into the client class.
-  Add a Kubernetes class to the client pkg
=> Create a Kubernetes Client struct

scripts/prep_local_devel_env.sh, templates/k8s-ansible-service-broker.yaml.j2, templates/k8s-local-dev-changes.yaml
After the etcd ssl work landed, the broker and etcd
pods were split and the etcd deployment name changed.
Realign the k8s templates with those changes.
- Have k8s use the same resources names as the openshift templates
Partially-fixes: https://github.com/openshift/ansible-service-broker/issues/233
=> Rebase k8s templates to pickup etcd name change

pkg/apb/executor.go, pkg/apb/provision_or_update.go, pkg/apb/secrets.go, pkg/apb/svc_acct.go, pkg/app/app.go, pkg/app/config.go, pkg/clients/kubernetes.go, pkg/handler/handler.go, pkg/registries/adapters/local_openshift_adapter.go
Revert a portion of the k8s struct patch. We need to pass the log object in for each call.
=> Give cluster client the log object

scripts/broker-ci/cleanup-ci.sh, scripts/prep_local_devel_env.sh, templates/deploy-local-dev-changes.yaml, templates/k8s-local-dev-changes.yaml
A bunch of fixes when running locally.
- Deleting the asb service causes issues. The service-ca (asb-tls) gets deleting causing later prep_local_dev_env runs to fail and the catalog fails to connect to the broker.
- Use the proper path when deleting ci resources
- Use a deployment config for asb-etcd
- Point the asb-etcd resources at the etcd app and service
- Remove the BROKER_PORT variable since it was causing an issue with template rendering and isn't needed
=> Few fixes to the local deploy templates

docs/proposals/prop-apb-gen-creds.md, pkg/apb/bind.go, pkg/apb/bind_test.go, pkg/apb/deprovision.go, pkg/apb/executor.go, pkg/apb/ext_creds.go, pkg/apb/ext_creds_test.go, pkg/apb/provision_or_update.go, pkg/apb/types.go, pkg/apb/types_test.go, pkg/apb/unbind.go, pkg/apb/watch_pod.go, pkg/broker/broker.go, pkg/clients/kubernetes.go, pkg/dao/dao.go, pkg/registries/adapters/adapter.go, pkg/registries/registry.go, pkg/registries/registry_test.go, pkg/version/apbruntimeversion.go, pkg/version/apbversion.go, scripts/broker-ci/setup-broker.sh, scripts/openshift/deploy.sh
This change makes it so the broker can handle secrets that are created
by APBs when using the `asb_encode_binding` module.
- Update the broker so that it can handle secrets generated by the APB
when `asb_encode_binding` module is used from the asb-modules.
- Update `executor::ExecuteApb` to wait for pod to complete, since the
pod is no longer kept alive for credential extraction.
- Clean up some of the log messages and code format related to apb
actions.
Fixes #544 
Fixes #553 
Implements the proposal #550 
Depends on the following PRs:
- [ansible-asb-modules#8](ansibleplaybookbundle/ansible-asb-modules#8) This is how the secret gets generated.
- [apb-base#7](ansibleplaybookbundle/apb-base#7) Remove scripts related to extracting credentials from the containers filesystem.
- …
=> Broker should extract credentials from secret

pkg/app/app.go, pkg/runtime/runtime.go, pkg/runtime/runtime_test.go
Contact the openshift version endpoint to verfiy what cluster
the broker is running on.  If the openshift endpoint isn't present, the
broker is running on kubernetes.
- Identify which cluster the broker is running on
=> Identify the cluster in the NewRuntime call

README.md
- 3.6.0 is no longer supported by the "Getting Started" demo
- The workflow for binding changed from what is described in the "Getting Started" demo
=> fixes README to reflect behavioral changes

pkg/broker/broker.go, pkg/broker/util.go, pkg/broker/util_test.go
Will add debug messages when a type from an APB parameter is not defined, and remove from the services for catalog.
- add error handling to SpecToService
fixes #388
=> Adding ability to warn and filter out bad specs.

CONTRIBUTING.md
The user will see namespaces "ansible-service-broker" and "kube-service-catalog". This clarifies what they should expect to see.
=> fixes a typo and clarifies the name of "kube-service-catalog"

pkg/clients/openshift.go, pkg/handler/handler.go, pkg/registries/adapters/adapter.go, pkg/registries/adapters/local_openshift_adapter.go
Update the local openshift adapter to read the runtime version off of
the image.
=> Resolve runtime version from local openshift

pkg/handler/handler.go
Updating the status code for when a user does not have access to do an apb action
fixes bug 1510486
=> Bug 1510486 - Return 403 for disallowed actions

CONTRIBUTING.md, Makefile
I was continually running into unexpected behavior while resetting my catasb. Turns out the certs / tokens were getting regenerated in the cluster but were not being exported on my `make run`s because the files already existed.
I believe local developers should have an explicit "prep-local" target designed to setup a local environment with exported credentials, and a separate "make run" that is as thin as possible to facilitate rapid development iteration and testing.
=> Make prep-local explicit and update docs

docs/proposals/Network-Isolation.md
This PR will define how we can deal with joining networks that are isolated to allow APBs to talk to the resulting pods that it creates over the network.
- Implement interface and initial implementation for `redhat/ovs-multitenant` network plugin
=> Initial proposal for dealing with network isolation SDNs

pkg/app/app.go, pkg/app/args.go
`asbd --help` was showing help once and then again as an error.  All errors were printing twice.  I remove the extra println to remove the duplicate and return a 0 exit code if the command arg `--help` was used.
=> Bug 1525817 - remove duplicate help output and return 0 exit code.

templates/simple-broker-template.yaml
The [**Up and Running with OpenShift Ansible Broker**](https://github.com/jmrodri/blogs/blob/master/up-and-running.md) blog needs a simple template.
TEST
---------
```
oc cluster up --service-catalog=true
oc login -u system:admin
oc new-project ansible-service-broker
cat templates/simple-broker-template.yaml | oc process -n "ansible-service-broker" -f - | oc create -f -
```
=> Simple template to support my blog post

pkg/broker/broker.go, pkg/broker/util.go, pkg/broker/util_test.go
The error message when failing to parse a spec is improved to include the name
of the spec.
fixes #592
=> allows parameter types to be case-insensitive

templates/deploy-ansible-service-broker.template.yaml
The PR adds the local openshift adapter to the template.
Problem is, with the `master` version of the `templates/deploy-ansible-service-broker.template.yaml`, and the `scripts/run_latest_build.sh` files, it is not possible to perform an `apb push` (with latest apb-tools).
The call succeeds, but the apb is not added.
On IRC @shawn-hurley told me that it's because I dont have the local openshift adapter. 
So I am adding it here
- adding local openshift adapter to the template
nope
=> Adding local openshift adapter

pkg/broker/deprovision_job.go, pkg/broker/deprovision_subscriber.go, pkg/broker/provision_job.go, pkg/broker/provision_subscriber.go, pkg/broker/types.go, pkg/broker/update_job.go, pkg/broker/update_subscriber.go
There were 3 different JobMsg types being used however they were all essentially the same barring one field and all consumers of the type were using the interface: WorkMsg 
- remove the provisionmsg, deprovisionmsg and updatemsg type and replace them with a single jobmsg type
=> Remove the different job msg types to avoid duplication of code

pkg/config/config.go, pkg/config/config_test.go, pkg/registries/registry.go
This fixes a bug in the configuration package that caused multiple registries to be initialized.
- make it so that you don't use both keys of name and type, but rather name then type.
- remove debug statement that should be removed.
fixes #605
=> The config should only use type as a key when name does not exist.

pkg/apb/provision_or_update.go, pkg/apb/types.go, pkg/apb/watch_pod.go, pkg/broker/broker.go, pkg/broker/deprovision_job.go, pkg/broker/deprovision_subscriber.go, pkg/broker/provision_job.go, pkg/broker/provision_subscriber.go, pkg/broker/update_job.go, pkg/broker/update_subscriber.go, pkg/registries/adapters/local_openshift_adapter.go
* Make it so that job state holds errors from apb package
* Make it so de/provision/update/_job can get the error and handle correctly.
* make sure that the broker/handler handles the error and returns
* Warn when about permissions for specs that may not be pullable.
Fixes bug 1512042 by adding more explicit warning logs and handing errors back to the user.
Bug 1512042
=> Bug 1512042 - Allowing error messages to make it from apb to user.

pkg/broker/broker.go
in last operation there was an incorrect if statement causes excess logging 
```
job state has an error. Assuming that any error here is human readable. err - 
```
- fix the if statement so it only logs if there is an error
=> fix incorrect check in if statement

pkg/apb/watch_pod.go
This is minor fix for an issue that resulted in https://github.com/openshift/ansible-service-broker/issues/612, But is likely not the full resolution though.
- containerStatus.State.Waiting is a pointer and so can be nil.
=> fix potential nil pointer panic

pkg/registries/filter.go, pkg/registries/filter_test.go
Handles case when the yaml looks like
```yaml
registry:
...
white_list:
- ""
....
```
- Test case for the use case
- If block to ignore regex strings that are zero value or `""`
Bug 1526887
=> Bug 1526887 - Handle case when whitelist/blacklist set to ""

pkg/handler/handler.go
Switch to using the same routing prefix for the apb tool endpoints. The apb tool has all the information needed to use these endpoints.  
partially: https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/issues/180
=> Use the router prefix for apb tool endpoints

pkg/apb/executor.go
Fixes a typo in a log statement
=> fixes typo in a log statement

pkg/apb/types.go, pkg/apb/types_test.go, pkg/broker/util.go, pkg/registries/registry_test.go
Updated apb spec to allow for more validations from JSON Schema. 
https://datatracker.ietf.org/doc/draft-handrews-json-schema-validation/
Validations follow JSON schema keywords, and uses snake_case instead of camelCase for consistency when writing APBs
Added apb_field (JSON schema field):
- max_length (maxLength)
- min_length (minLength)
- multiple_of (multipleOf)
- minimum (minimum)
- maximum (maximum)
- exclusive_minimum (exclusiveMinimum)
- exclusive_maximum (exclusiveMaximum)
Allow maxlength to be used for backwards compatibility as DeprecatedMaxlength.
Allowed `type: integer` since it's used in JSON schema
=> Bug 1472226 - Add additional field validations for JSON Schema.

build/entrypoint.sh
Previously, a bash process would stay running all the time, and the broker
would be a child process of it. It is a best practice when building containers
to use "exec" to avoid such unneccessary parent processes.
**Changes proposed in this pull request**
- use "exec" in the entrypoint script
Before this change, you can see the extra bash process sitting around as PID 1:
```
$ oc exec -it asb-2-7rd7b -- ps -awfux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ansible+    20  0.0  0.0  47456  3240 ?        Rs+  19:40   0:00 ps -awfux
ansible+     1  0.0  0.0  11652  2412 ?        Ss   18:32   0:00 bash /usr/bin/entrypoint.sh
ansible+     9  0.2  0.3 283316 46148 ?        Sl   18:32   0:10 asbd -c …
```
=> uses "exec" so bash process gets replaced instead of retained

.travis.yml, pkg/app/app.go, pkg/clients/kubernetes.go, pkg/registries/registry.go, pkg/registries/registry_test.go, templates/deploy-ansible-service-broker.template.yaml
* This was in place and was changed most likely due to a bad rebase.
- Re-adding getting of secrets if auth type is secret
- Re-adding of getting of secrets from file if auth type is file
- Re-adding dealing with plain text config auth
This is tied to PR: #628 
fixes BZ 1533208
This was intially added in PR: https://github.com/openshift/ansible-service-broker/pull/502
=> Bug 1533208 - Re adding registry auth as secrets and files

scripts/run_latest_build.sh
This PR will default the `PUBLIC_IP` to the localhost. 
This value will allow for macOS to have this value because it can not find the docker interface `docker0`.
The issue that used to exist where the service catalog could not contact the broker is no longer a concern
fixes #588
=> Bug 588 - Run latest build with a default public ip.

pkg/registries/adapters/openshift_adapter.go
`HERE` is an atrocious debug statement. This must have been accidentally left in somewhere along the line.
=> Fix debug statement for ISV registry to be more verbose

pkg/app/app.go, pkg/broker/binding_job.go, pkg/broker/binding_subscriber.go, pkg/broker/broker.go, pkg/broker/types.go, pkg/broker/unbinding_job.go, pkg/broker/unbinding_subscriber.go, pkg/handler/handler.go, pkg/handler/handler_test.go, pkg/metrics/metrics.go
The async bind feature is used to allow binds that need more time to execute than the 60 seconds response time allotted in the Open Service Broker API spec. Async bind will spawn a binding job and return the job token immediately. The catalog will use the last_operation to monitor the state of the running job until either successful completion or a failure.
There are no new dependencies for this feature.
There is a new binding_subscriber to monitor the JobMsgs sent from the new binding_job. The Bind method in the broker was updated to take in the async flag and determine if it should spawn an APB for bind or simply return what was already stored like it did before.
Another set of critical additions was the new getserviceinstance and getbind calls added to the handler. These are to …
=> Async bind feature

pkg/registries/registry.go
Does not wipe out user/pass credentials just because the user didn't set auth_type. Later down the line we can explicity require auth_type if desired but it's not intuitive to set that value for long time users. This bit QE and the code was not in master for awhile so we weren't seeing this.
- Accept registry user/pass if auth_type is not set
=> Bug 1526949 - Set registry user/pass if auth_type is not defined

pkg/broker/broker.go, pkg/handler/handler.go
Unbind was not checking this previously. When doing an async unbind, this meant
multiple APBs got launched. Additionally, all but the first DELETE requests
were geting a 500 response code due to incorrect handling of "err" in code.
fixes #640
=> Bug 1534715 - unbind checks for existence of binding before trying to delete it

scripts/broker-ci/gather-logs.sh
CI sometimes fails on an apb or an errored out pod. Let's gather more information if we find a pod that
has errored.
- Improve CI logging when a pod fails
=> Print information on any pod failures

pkg/app/app.go
Allows for the unauthorized requests to be returned as JSON
* Thanks to Jordan Liggitt for helping me diagonse this one
* The apiserver codec/seriallizer did not know how to deal with our
unversioned api.
**fixes (This will close that issue when PR gets merged)**
fixes 1534467
=> Bug 1534467 - apiserver was not told how to output error response

pkg/broker/broker.go, pkg/broker/unbinding_job.go, pkg/handler/handler.go, pkg/handler/handler_test.go
This matches how ServiceInstance retrieval takes place.
re #640
=> Bug 1534715 - Moves BindInstance retrieval and error handling to handler.go

pkg/broker/broker.go, pkg/handler/handler.go, pkg/handler/handler_test.go
=> Bug 1535652 - return 200 to bind PUT when a binding already exists

pkg/apb/executor.go, pkg/apb/types.go
* Broker should inspect its own enviornment, and in the presence of
a proxy configuration, should apply those settings to executing APBs.
=> Bug 1506978 - Apply proxy settings to running APBs

pkg/app/app.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/testdata/generated_local_development.yaml
Adds ability for the config package to handle an array of elements 
**Changes proposed in this pull request**
* Fixing registry unique name regression.
* Adding ability to get an array of sub configs.
* Handling the case that final object is an array will return an array
now.
* if not the final key, will still attempt to look into an array based on
the name then type.
fixes #644
=> Bug 1535182 - adding ability to retrieve an array of sub configs

templates/k8s-ansible-service-broker.yaml.j2
The clusterrole was missing some networking permissions. Also, remove the perms for openshift.io.
- Add networking policy to the asb-auth clusterrole
fixes https://github.com/openshift/ansible-service-broker/issues/651
=> Add some missing networking permissions to the k8s template

scripts/broker-ci/setup-broker.sh
Sometimes travis fails because of mirror timeouts when building
containers.  The retry logic around make build-image was suppose
to mitigate these failures, but it wasn't retrying.
- Add ```+e``` for error tolerance when running ```make build-image```
=> make build-image isn't retrying

pkg/apb/executor.go, pkg/apb/types.go
I managed to break the linter with the `ProxyConfig`. Satisfies `make check`. Glorious green. (I'm officially protesting the idea this a good field name. It's so ugly.)
=> Fix linting on ProxyConfig

pkg/handler/handler.go, pkg/handler/handler_test.go
=> Bug 1536088 - fixes panic when bind can't find ServiceInstance

pkg/apb/types.go, pkg/broker/binding_job.go, pkg/broker/binding_job_test.go, pkg/broker/binding_subscriber.go, pkg/broker/broker.go, pkg/broker/deprovision_job.go, pkg/broker/deprovision_subscriber.go, pkg/broker/provision_job.go, pkg/broker/provision_job_test.go, pkg/broker/provision_subscriber.go, pkg/broker/provision_subscriber_test.go, pkg/broker/types.go, pkg/broker/unbinding_job.go, pkg/broker/unbinding_job_test.go, pkg/broker/unbinding_subscriber.go, pkg/broker/update_job.go, pkg/broker/update_subscriber.go
**Note for Reviewer**
There are two commits here
1) making the changes required
2) adding a set of test for the provision subscriber and job. If happy with the approach here I will expand the tests to cover the other subscribers and jobs.  Making a number of changes like this, I felt a little disconcerted that I had no unit test to run so would love to add more to help protect against regressions in future changes.
These commits are independent of each other so if the new tests are not wanted I can remove.
I am currently trying this out in my local cluster but wanted to create the PR to let the integration tests run.
The subscribers were deciding on the state of the Job, rather than the job informing the subscriber of the job state.  This …
=> Bug 1536629 - send job state and credentials from job

cmd/broker/main.go
The concern stands; we still want to consider graceful exit, but @maleck13 has raised some good points in #614 that sound like they're more golang-ish.
=> Remove ancient comment with app startup

pkg/handler/handler.go
PR does nothing but remove a very old header check that has been commented out. Background on this is when we inherited our original http server from the template broker, it was checking for the presence of the `X-Broker-API-Version`, [which MUST be sent by the platform to brokers](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#api-version-header). The broker has no obligation with regard to this header; it's there in case brokers rely on features that may not be present in the platform they're currently talking to. IIRC, I created this issue because at the time, the catalog was not sending the header.
I'm removing the comment (and want to close the issue) because I don't see an immediate need for us to …
=> Remove platform version header check comment

.travis.yml, scripts/travis.sh
**Describe what this PR does and why we need it**
Everything that runs in the scripts section won't error out on a failure. Move everything that is part of the setup for the CI job out of the scripts section so we fail faster if the setup fails.
=> Fail faster with travis

ansible-service-broker.spec, pkg/apb/deprovision.go, pkg/apb/types.go, pkg/apb/unbind.go, pkg/broker/broker.go, pkg/dao/dao.go, pkg/handler/handler.go, pkg/handler/io.go
Reduced the *TODO* count from 60 to 38.
```
$ git grep TODO| grep -v vendor | wc -l                                                                 
60                                   
$ git grep TODO | grep -v vendor | wc -l
38
```
fixes #665
=> fixes #665 - remove many of the TODOs

.travis.yml
We don't need to run CI on doc changes so exit early.
- Check to see that only docs are being changed, then exit 0.
=> Skip running the travis job if we're only changing docs

pkg/broker/broker.go, pkg/broker/types.go, pkg/handler/handler.go, pkg/handler/handler_test.go
Previously the http response incorrectly had code 201.
Once async logic was removed from buildBindRequest, it looked an awful lot like
a simple constructor. That's why I moved it next to the type definition and
renamed it NewBindRequest to match golang convention.
fixes #667
=> Bug 1536659 - bind PUT returns http code 202 when operation runs async

docs/README.md, docs/debugging.md, docs/troubleshooting.md
Add a debugging guide for the broker
=> add ASB debugging guide

.travis.yml, pkg/app/app.go, scripts/broker-ci/gather-logs.sh, scripts/broker-ci/setup-catalog.sh
Fix:
- ```git diff FETCH_HEAD...$TRAVIS_BRANCH``` was always returning true.  Instead, just use ```git diff $TRAVIS_BRANCH``` it will compare the diff from the current PR branch to the master branch.
Improvement:
- Use the freshly built service-catalog images
- Reduce service-catalog log-level to 2
- Only gather logs from the service-catalog from the last 5 minutes.
- List the docker images that travis has
=> One CI fix and a few improvements

pkg/apb/executor.go
* We've seen the boto (*not* boto3) python lib expecting lowercase
"http_proxy". Need to also include lowercase variants.
=> Bug 1506978 - Include lowercase proxy vars

pkg/registries/adapters/dockerhub_adapter.go, pkg/registries/adapters/openshift_adapter.go, pkg/registries/adapters/rhcc_adapter.go
When a spec fails to load, it will cause all the specs from that registry adaptor to be ignored.  If the broker is configure to look at only one adaptor, it causes the broker to fail.
Let's log the spec failure and continue processing valid specs.
- Be more fault tolerant to failed specs
fixes https://github.com/openshift/ansible-service-broker/issues/681
=> Bug 1538321 - Continue to load specs even when a spec fails to load

pkg/handler/handler.go, test/last_operation_bind.sh
Missing last_operation for the async binds. The service_instance method would work because our jobs are the same. But OSB platforms will want to call the last_operation binding.
=> Bug 1537367 - missing last_operation for bindings

pkg/broker/binding_job.go, pkg/broker/binding_job_test.go, pkg/broker/broker.go, pkg/broker/deprovision_job.go, pkg/broker/deprovision_subscriber.go, pkg/broker/provision_job.go, pkg/broker/provision_job_test.go, pkg/broker/unbinding_job.go, pkg/broker/unbinding_job_test.go, pkg/broker/update_job.go
This reverts commit 154ddf91359d990a69db2aeabe1f620348155d73.
The original PR is more of tech-debt than actual bug fix. We don't want
that in the 1.1 release (OpenShift 3.9).
=> Revert "Bug 1536629 - Send job msg immediately as job starts.

.tito/releasers.conf
adding a 3.10 releaser, the brew tag doesn't exist yet but it will prevent you from building 3.10 into 3.9.
=> add a 3.10 releaser

pkg/clients/openshift.go, pkg/handler/handler.go
Allows the Subject Rules Review to do the full check.
- Pass groups and extras to Client for validation
- Pull out openshift scopes from extras
- Pass groups and scopes to SRR Spec
fixes bug 1538732
=> Bug 1538732 - Adding ability for Subject Rules Review to do the correct check.

pkg/handler/handler.go
Adds a default error to deprovision handler
- Return a 500 status code as a fallback
fixes https://github.com/openshift/ansible-service-broker/issues/698
=> Add fall through case to deprovision handler

pkg/broker/broker.go, pkg/handler/handler.go, pkg/handler/handler_test.go
Previously it was incorrectly returning response code 200 when the operation
ran asynchronously.
fixes #701
Reviewed and approved here: https://github.com/openshift/ansible-service-broker/pull/702
=> Bug 1539757 - async unbind returns http 202

scripts/broker-ci/wait-for-resource.sh
Sometimes a pod will show a 'Running' status before all the containers are available.
=> Check that all the containers in a pod are running

docs/proposals/bind-job-state.md
Please provide feedback plus any other potential solutions you think are worth consideration.
Of the three I described, my least-favorite is the "JobState.Resource" option.
=> Proposes solutions for tracking state of BindInstance creation

templates/simple-broker-template.yaml
reverts the image to a version that is compatible
=> Revert image back to match blog post in simple broker template.

pkg/apb/bind.go, pkg/apb/deprovision.go, pkg/apb/provision_or_update.go, pkg/apb/unbind.go, pkg/apb/watch_pod.go, pkg/clients/kubernetes.go
apb-base will now return a non-zero exit status meaning the pod will be marked as failed when an action that doesn't exist is used. For example, calling bind on an apb that does NOT have a bind.yaml. 
PR depends on 2 others to satisfy the bugzilla:
apb-base: https://github.com/ansibleplaybookbundle/apb-base/pull/17
=> Bug 1533425 - handle missing pod action error

pkg/broker/broker.go, pkg/handler/handler.go
Fix a bug
- Drop requested parameter updates with invalid enum values
Doesn't depend on anything else.
=> Bug 1538986 - Remove bad enum values from Update Request

pkg/registries/registry.go, pkg/registries/registry_test.go
Give full respect to the whitelist config value by no longer filtering for '-apb'.
- Remove hardcoded filter on the suffix '-apb'
fixes https://github.com/openshift/ansible-service-broker/issues/685
=> No longer only search for apbs that end with -apb

pkg/broker/update_job.go
Ensure we check the extCred for nil.
=> Bug 1541265 - avoid broker panic, check for nil

pkg/app/app.go, pkg/broker/binding_subscriber.go, pkg/broker/broker.go, pkg/broker/deprovision_subscriber.go, pkg/broker/unbinding_subscriber.go, pkg/broker/update_subscriber.go, pkg/dao/dao.go, pkg/dao/etcd/dao.go
Having an interface for the DAO will allow us to switch persistent layers. This will also allow for unit testing in other parts of the code base.
- move etcd dao into dao/etcd package
- everything should now use the DAO interface
fix for PR #722 Work Item 1
This fixes #542
=> Dao Interface

docs/proposals/custom_resources_definitions.md
Proposal for using custom resource definitions.
=> Initial prop for custom resource definitions

pkg/auth/auth_test.go
The print message should be fatalf since it includes a variable.
This also fixes the gate.
=> Fix vet test

scripts/kubernetes/resources.sh, scripts/prep_local_devel_env.sh, templates/deploy-local-dev-changes.yaml, templates/k8s-local-dev-changes.yaml
When using labels on the endpoint, we're associating the endpoint to an object that may not always be around, the locally running broker. This seems to cause the endpoint lose it's ip address. Instead, make the endpoint have no association to an app so it will always be around.
- Keep the endpoint ip address around all the time
fixes https://github.com/openshift/ansible-service-broker/issues/660
=> Make the endpoints headless for local brokers

pkg/broker/broker.go, pkg/handler/handler.go
* Filters unchanged parameters from update requests
* Returns 400 error when a user requests updating a non-updatable parameter
fixes #732 
I'm labeling this as DO-NOT-MERGE because I want to close #732 with this as well. Quoting here:
> There are a couple branches of parameter validation where we are ignoring erroneous inputs:
> * Users passing updated parameters that don't exist on a plan.
> * Users passing enum values that aren't part of the acceptable set of values.
>
> In both cases, we strip them from the request parameters. I think they should be Bad Request 400s, mainly because I think these represent a user's …
=> Bug 1540121 - Return 400 for bad update requests

pkg/broker/broker.go
* These logs suggest an unexpected error has occurred if broker::GetServiceInstance
fails to find the instance. During the normal deprovision cycle, we will
likely see multiple requests to deprovision the same instance. This
method is called in the deprovision handler before it ever hits
broker::Deprovision, so it's entirely normal for these etcd gets to
miss. Therefore, these really aren't errors. Still useful to log
however, as info.
=> Bug 1539308 - Do not report errors on dupe depros

pkg/registries/adapters/rhcc_adapter.go
Previous logging output was not helpful in determining the issue. Before we were getting 'invalid character' in the logs along with "Got Image Response from RHCC".
Now if RHCC fails to bootstrap it returns the status response (for current bug):
```
[2018-02-07T09:32:26.16-05:00] [ERROR] - unable to retrieve image names for registry rhcc - 500 INTERNAL SERVER ERROR
```
=> Bug 1542387 - Print out status of response from RHCC registry if not 200

ansible-service-broker.spec
This branch needs its own version to avoid collisions with official release branches.
=> Avoid version collisions

pkg/broker/types.go, pkg/clients/openshift.go, pkg/handler/handler.go
Will allow us to handle scope that has been incorrectly encoded
- Deal with the other way of encoding scopes
- Default to close if both scopes are preset
=> Bug 1541461 - Deal with buggy encoded scopes from service catalog.

scripts/broker-ci/setup.sh
adds the tag for the apb  images for the release 1.0 branch
=> adding sprint139 images for 1.0 release CI

pkg/apb/executor.go, pkg/apb/types.go, pkg/apb/types_test.go, pkg/broker/binding_subscriber.go, pkg/broker/broker.go, pkg/broker/deprovision_subscriber.go, pkg/broker/provision_subscriber.go, pkg/broker/provision_subscriber_test.go, pkg/broker/types.go, pkg/broker/unbinding_subscriber.go, pkg/broker/update_subscriber.go, pkg/dao/dao.go
The broker now stores a reference to a bind job with the BindInstance, so that
it can be looked up in the future if successive equivalent requests are
received.
fixes #670
The solution was discussed here: https://github.com/openshift/ansible-service-broker/pull/680
=> Bug 1543521 - Fix async bind with job already in progress.

scripts/run_latest_build.sh
Some good regex practice 😃 .
Sample output:
```
WARNING: Using client version: v3.7.0 with cluster version: v3.9.0-alpha.3
```
fixes https://github.com/openshift/ansible-service-broker/issues/752
=> Warn the user when using an old client

scripts/broker-ci/setup.sh, templates/deploy-ansible-service-broker.template.yaml
Make it so things in the `release-1.0` branch use `release-1.0` images + packages + etc.
=> Lock down everything in branch to this release

pkg/apb/types.go, pkg/broker/broker.go, pkg/dao/dao.go, pkg/dao/etcd/dao.go
Currently, we save a mapping between names and id and have the data in
the spec already.
This was a convenience method to quickly get that data, but when moving
to CRDs I don't think we should create a resource for a single value
mapping
- Remove all interface and implementation methods for plans
- Add helper method on spec to get plans from ID
- Remove pointer to spec values memory when getting plans. Makes it more memory safe
=> Remove plan dao methods

pkg/apb/bind.go, pkg/apb/deprovision.go, pkg/apb/provision.go, pkg/apb/provision_or_update.go, pkg/apb/types.go, pkg/apb/unbind.go, pkg/apb/update.go, pkg/apb/watch_pod.go, pkg/apb/watch_pod_test.go, pkg/broker/binding_job.go, pkg/broker/binding_job_test.go, pkg/broker/broker.go, pkg/broker/deprovision_job.go, pkg/broker/deprovision_job_test.go, pkg/broker/deprovision_subscriber.go, pkg/broker/deprovision_subscriber_test.go, pkg/broker/provision_job.go, pkg/broker/provision_job_test.go, pkg/broker/types.go, pkg/broker/unbinding_job.go, pkg/broker/unbinding_job_test.go, pkg/broker/update_job.go, pkg/broker/update_job_test.go, pkg/broker/update_subscriber.go, pkg/broker/update_subscriber_test.go, pkg/broker/work_engine.go, pkg/broker/work_engine_test.go, pkg/mock/dao.go
broker implementation for issue 475 last operation description
**Note**
This pr is based on top of the previous PR https://github.com/openshift/ansible-service-broker/pull/610 so probably better to review once that one is closed out. 
- Add new channel that sends JobState changes asynchronously to allow the state to be updated ready for the last operation polling endpoint to read.
- Add sets of tests for various places that have been changed.
- change the watch pod to use the watch API
- Add StartSyncJob to unify the broker Job API
~~depends-on https://github.com/openshift/ansible-service-broker/pull/610~~
depends-on …
=> 475 last operation description

pkg/broker/broker.go, pkg/broker/types.go, pkg/broker/util.go
the async bind spec change requires bindings_retrievable when we support
async binding for a service. We are taking the approach that if an apb
is bindable, it will support async bind.
fixes BZ 1539542 https://bugzilla.redhat.com/show_bug.cgi?id=1539542
=> Bug 1539542 - return bindings_retrievable

templates/k8s-ansible-service-broker.yaml.j2
This PR adds the required configuration value `openshift.namespace`
=> add namespace config to k8s deployment template

pkg/broker/broker.go, pkg/broker/unbinding_subscriber.go, pkg/handler/handler.go
Ready for review
- If job already in progress return correct status code to handler
- Wrap clean up of unbind process in function, which can be called from async job or broker
fixes #709
=> Fix last op endpoint unbind response

.tito/releasers.conf
Doing this will prevent future self from accidentally releasing to the
wrong downstream branch.
=> Lock asb-brew releaser to 3.9 branch

.tito/releasers.conf
Doing this will prevent future self from accidentally releasing to the
wrong downstream branch.
=> Lock asb-brew releaser to 3.10 branch

.tito/releasers.conf
Doing this will prevent future self from accidentally releasing to the
wrong downstream branch.
=> Lock asb-brew releaser to 3.8 branch

docs/filtering_apbs.md, pkg/registries/filter.go, pkg/registries/filter_test.go, pkg/registries/testdata/empty_whitelist.yaml
We currently filter nothing when blacklist is empty and whitelist is empty. 
Another way of saying this is if I have this whitelist config:
```yaml
white_list:
- ".*-apb$"
```
In my registry I have nothing that ends in ```*-apb```.  The result is that everything goes unfiltered.
```
[2018-02-21T12:12:20.868-05:00] [DEBUG] - APBs passing white/blacklist filter:
[2018-02-21T12:12:20.868-05:00] [DEBUG] - -> docker.io/centos/python-36-centos7
[2018-02-21T12:12:20.868-05:00] [DEBUG] - -> docker.io/centos/postgresql-95-centos7
[2018-02-21T12:12:20.868-05:00] [DEBUG] - -> docker.io/openshift/mongodb-24-centos7
[2018-02-21T12:12:20.868-05:00] [DEBUG] - -> docker.io/openshift/jenkins-2-centos7
[2018-02-21T12:12:20.868-05:00] [DEBUG] - -> …
```
=> Filter everything when whitelist is empty

README.md
This adds documentation for how to install and run the broker in a pure kubernetes environment. This is needed by potential users who are not on openshift.
- Split the "Getting Started" guide into two sections; one for kubernetes and one for openshift.
=> Adds docs for installing the broker in minikube

README.md
A lot of people are following the minishift link to the currently broken minishift/minishift-addons repo. This links to my correct fork, and adds a temporary note until the PR is merged.
=> Temporarily link to minishift-addons fork

pkg/broker/deprovision_subscriber.go
Forward port of #790 to master
=> Bug 1548311 - Return success on depro extcred miss

docs/proposals/extracted_credentials_saved_as_secrets.md, pkg/apb/bind.go, pkg/apb/deprovision.go, pkg/apb/executor.go, pkg/apb/ext_creds.go, pkg/apb/mock_executor.go, pkg/apb/provision.go, pkg/apb/provision_or_update.go, pkg/apb/unbind.go, pkg/apb/update.go, pkg/app/app.go, pkg/broker/binding_subscriber.go, pkg/broker/broker.go, pkg/broker/deprovision_subscriber.go, pkg/broker/deprovision_subscriber_test.go, pkg/broker/jobs.go, pkg/broker/provision_subscriber.go, pkg/broker/provision_subscriber_test.go, pkg/broker/types.go, pkg/broker/unbinding_subscriber.go, pkg/broker/update_subscriber.go, pkg/broker/update_subscriber_test.go, pkg/clients/kubernetes.go, pkg/dao/dao.go, pkg/dao/etcd/dao.go, pkg/runtime/extracted_credentials.go, pkg/runtime/runtime.go
=> Save extracted credentials into a secret

README.md
* Updates link to correctly point to minishift/minishift-addons instead
of eriknelson fork now that the PR has been merged.
=> Remove tmp note re: minishift-addon

templates/deploy-ansible-service-broker.template.yaml
use the NAMESPACE var in the deployment template where applicable.
=> parameterize the 'ansible-service-broker' namespace w/ NAMESPACE var

build/Dockerfile-canary
Force canary images built on the master branch use code from the master branch.
=> Force canary image be built from master

build/Dockerfile-canary
Make it so that canary images built from this branch actually contain the code from this branch.
=> Force canary image be built from release-1.1

build/Dockerfile-canary
Make it so that canary images built on this `release-1.0` branch use the broker code from this branch.
=> Force canary image be built from release-1.0

pkg/app/app.go, pkg/broker/broker.go, pkg/clients/clients.go, pkg/clients/crd.go, pkg/dao/crd/conversion.go, pkg/dao/crd/dao.go, pkg/dao/dao.go, pkg/dao/etcd/dao.go, templates/deploy-ansible-service-broker.template.yaml, templates/k8s-ansible-service-broker.yaml.j2
Implements Broker client dao.
-  Adds a config value for CRD dao
- Adds implementation for conversion and dao from CRD to apb package structures
~~#775~~
~~#794~~
=> Broker client dao

docs/proposals/subscriber-fan-in-fan-out.md
Proposal based on conversations with the team about the current subscriber pattern and some of its weaknesses. 
This proposal is fairly complete in my opinion but keen to get feedback on the approaches outlined and to ensure I am fulfilling everyone's expectations around this change.
fixes #638
=> Initial pass at proposal to change subscribers

README.md, docs/README.md, docs/apb_integration.md
Updating Markdown files, where the links were pointing to the older `fusor` org. on Github.
- fixing broken links (e.g. the rocketchat-apb link)
- updating links to point to the newer ansibleplaybookbundle GH org
This PR is independent, and has no link/relationship to any other PR - it's mainly for updating (slightly) outdated markdown filez
=> Removing links to older fusor GH org

docs/README.md, docs/service-bundle.md
This document captures a detailed description of the existing contract between a Service Bundle and the Automation Broker.
Please review how accurately this represents the current relationship between a Service Bundle and the Automation Broker as implemented today. Please do not (yet) review the technical merits of this design. Once this document is reviewed and accepted as an accurate representation of reality, a next step will be to review the design on technical grounds and look for opportunities to improve it.
=> Adds Service Bundle contract document

scripts/release_notes.sh
When a Sprint is over and I need to create release notes, I want to know what was the last commit I looked at for the previous Sprint. This adds breadcrumbs to make that easier.
=> Add breadcrumbs to release notes

pkg/broker/unbinding_subscriber.go
Delete leftover deletion of extracted credentials in the broker package.
fixes #819
=> remove extra deletion of extracted credentials in broker package

templates/deploy-ansible-service-broker.template.yaml
Having a default policy of only allowing APBs with a name suffixed by "-apb" has been confusing our development community. This change removes the above restriction by default. The justification for this change is that the deployment environments that use this template from the github repo include catasb, minishift, and `run_latest_build.sh`. These are all specifically development environments. `openshift-ansible`, which is likely used for production deployments, carries its own production deployment template. 
fixes #823
=> Default to an open localregistry policy

scripts/run_latest_build.sh
* Run latest logs in as system:user, and it's surprising our developers
when they go to use the apb tool, as a non-token'd user will not work.
Adds a note calling this out to run_latest_build.sh
fixes https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/issues/242
=> Add a note to run latest about current user

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
The Feature heading in the issue template was so large the issue text
was sometimes lost.
The pull request template had inconsistent formatting.
=> make headings smaller

pkg/broker/broker.go
removes the overwriting of the job state.
**Race condition**:
Skip APB run -> send a successful message -> then broker code sets status to in progress.
Making the job run forever.
- Don't set the state to in progress if we are skipping the APB run.
fixes 1554239
=> Bug 1554239 - overwriting job state that has been finished.

docs/proposals/helm-charts.md
This describes a plan for supporting Helm Chart Repositories.
=> Proposal for Helm Chart Registry Adapter

docs/proposals/apb-state-support.md
Proposal outlining a new feature for storing state as an APB developer
fixes https://github.com/openshift/ansible-service-broker/issues/530
@jmrodri ping initial proposal.
=> APB state support

pkg/apb/watch_pod.go, pkg/broker/jobs.go
If the APB provision fails, this PR will check for a non-empty termination message, and will display it in the WebUI, instead of the generic error message.
fixes [#675](https://github.com/openshift/ansible-service-broker/issues/675)
=> Display Custom Error Message for the APB via termination-log

scripts/run_latest_k8s_build.sh
The kubernetes run latest script has the potential to filter for more than one token causing an error.  Only grab the token for the ansibelservicebroker-client sa.
=> Only grab the token the broker sa is using

docs/proposals/apb-state-support.md
Minor changes to ensure the proposal lines up with what will be done.
=> minor updates to proposal to clarify a few points

docs/service-bundle.md, pkg/broker/broker.go, pkg/broker/types.go, pkg/broker/util.go, pkg/handler/handler.go, pkg/handler/handler_test.go
username information was requested to be available for APBs
- pass the username info from the broker to the APB during it's executions as a parameter in extra_vars
* [Issue #674](https://github.com/openshift/ansible-service-broker/issues/674)
=> make username available for APB in the serviceInstance

docs/config.md, pkg/registries/adapters/openshift_adapter.go
Updates the `openshift` registry adapter so that it uses the www-auth redirect and doesn't require us to use registry.connect.redhat.com.
- Hit /v2/ to get www-authenticate header
- Follow redirect to get Bearer token
- Now attempt to get manifests
=> Bug 1558472 - Update openshift registry to use www-auth redirect header

Gopkg.lock, Gopkg.toml
Make sure that a dep ensure does not cause broker developer to get a newer version of bundle-lib than we expect.
=> Use the correct versions

scripts/run_latest_build.sh
Lots of folks use ```run_latest_build.sh``` with the apb tool.  But, when ```run_latest_build.sh``` completes, the script suggests the user login to the developer user in order to use the apb tool.  The developer user by default doesn't have permission to contact the broker in the ansible-service-broker namespace so the apb tool isn't going to work.
- Print a command to give the developer user cluster-admin
=> Remind the user to give the developer cluster-admin

pkg/dao/crd/dao.go
Instead of failing when a spec fails to load, warn there was and error and output to debug the error.
- No longer fail when we find a bad spec using crds
=> Warn in the logs that a spec failed to load and continue

.travis.yml, scripts/travis.sh
* this should make it easier to see what failed
* should allow for easier gate debugging
=> make more than one stage for all the tasks we want to do.

README.md
Updates documentation for starting minikube:
- enabling RBAC for minikube 
- removing specified version (minikube has only 1.9.0 or latest, current 1.9.3 didn't work)
only docs changes above 
no
none
=> Fix docs - enabling RBAC for minikube

.gitignore, Makefile, ansible-service-broker.spec, build/Dockerfile-canary, build/Dockerfile-localdev, cmd/migration/main.go
We need a way to migrate from ETCD to CRD for openshift ansible
- create a new command and add to RPM and Images
- connects to etcd and crd dao's and will convert etcd to crd
Trello: https://trello.com/c/KlFLeFI0
example job.yaml:
```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
name: asb-etcd-migration
spec:
parallelism: 1
completions: 1
template:
metadata:
name: asb-etcd-migration
spec:
containers:
- name: asb
image: 'docker.io/shurley/origin-ansible-service-broker:migration'
imagePullPolicy: Always
command:
- '/usr/bin/migration'
args:
- '-host=asb-etcd.ansible-service-broker.svc'
- '-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt'
- '-client-cert=/var/run/asb-etcd-auth/client.crt'
- '-client-key=/var/run/asb-etcd-auth/client.key'
- …
```
=> Add migration command

docs/service-bundle.md, pkg/broker/broker.go, pkg/broker/types.go
This PR exposes a new parameter `_apb_service_binding_id` to the bind role that contains the externalId of the associated service binding. This is useful in cases where you want to trigger `unbind` by deleting the service instance.
- Add `_apb_service_binding_id` to the injected parameters for the `Bind` action.
No
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1565648
ping @maleck13 @shawn-hurley
=> Bug 1565648 - expose _apb_service_binding_id to bind role

templates/simple-broker-template.yaml
Update the images used by the simple-broker-template to be release-1.1 branch.
```
$ docker run -it --entrypoint asbd docker.io/ansibleplaybookbundle/origin-ansible-service-broker:sprint142 --version
1.1.3
$ docker run -it --entrypoint asbd docker.io/ansibleplaybookbundle/origin-ansible-service-broker:release-1.1 --version
1.1.15
```
fixes #882
=> Issue 882 - Simple broker template should use release-1.1 instead of a sprint tag

scripts/broker-ci/setup-minikube.sh
This is a temporary workaround to https://github.com/kubernetes/minikube/issues/2704 until it's more clear exactly how to move forward, rolling back to an older version of minikube.
=> Pin travis to specific minikube version

pkg/broker/broker.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1567004
Without this, each synchronous bind operation (not using `launch_apb_on_bind`) creates a secret in broker namespace that will never get deleted. 
This appears to only be an issue with synchronous bind, as bundle-lib handles this in [unbind.go](https://github.com/automationbroker/bundle-lib/blob/master/bundle/unbind.go#L62).
- Add `apb.DeleteExtractedCredentials` call to the synchronous unbind code path
=> Bug 1567004 - Delete extracted credentials secret during synchronous unbind

scripts/run_latest_build.sh, scripts/run_latest_k8s_build.sh
Update scripts that deploy the broker to use the [`automation-broker-apb`](https://github.com/automationbroker/automation-broker-apb).
=> Update scripts to use the broker apb

pkg/app/app.go, pkg/auth/auth.go, pkg/broker/broker.go, pkg/broker/job_state_subscriber.go, pkg/broker/work_engine.go, pkg/dao/crd/dao.go, pkg/dao/etcd/dao.go
Making broker consistent with the log statements in bundle-lib, i.e. use
the *f version when logging formatting strings. It is most important
when using logrus, go-logging seems to handle it okay. But this PR will
make it easier to move to logrus in the future.
See PR #61 from bundle-lib for more information:
https://github.com/automationbroker/bundle-lib/pull/61
=> fix statements with formatting

build/Dockerfile-canary
Turns out that dockerhub doesn't allow you to configure the
build-context (unlike cloud.docker). However, since this is an openshift
repository, it isn't straightforward how to configure automated builds
for cloud.docker. Instead of wasting time trying to figure that out.
Just revert back to the git clone method for now.
=> Use git clone for canary

pkg/broker/broker.go, pkg/broker/types.go, pkg/dao/crd/dao.go
protect against simultaneous updates
Simultaneous calls to SetState or SetBindingInstance would fail with an already exists error instead of graciously updating the existing instances.
Also, the broker.Bind was incorrectly trying to set the state of a binding job using the instance id as the key, vs use bindingid for state in bindings
=> Bug 1533425 - protect against simultaneous updates

docs/design.md, docs/meetings/20170119-minutes.txt
Updates the old AA acronym (AnsibleApp) to APB (Ansible Playbook Bundle)
fixes #917
=> Update AA to APB in docs

apb/install.yaml
Turns out that I had already worked around the problem the project vs. namespace problem in the apb. If I let the apb create the project then there are no issues.
=> Run the apb in a different project

pkg/broker/broker.go, pkg/dao/crd/dao.go, pkg/handler/handler.go
* CRDs use the binding id alone switched to using binding id.
* Generate the statekey for use in etcd in the broker.go
* Make logs informative, some now include the k8s reason
* A conflicting update is now simply logged and skipped
=> Bug 1572470 - use binding id as instance, do not error on conflict

pkg/broker/broker.go
@shawn-hurley and I discovered a panic this morning. If for some reason the catalog has a bunch of instances that the broker is unaware of, the broker will try to lookup the instance, fail to find it, and panic when trying to deref the spec off a nil value. This correctly checks the error.
=> Add fix for get si npe

cmd/broker/main.go, pkg/app/app.go
Allows users to pass in their own custom registries into the Automation Broker. This means you can create a custom adapter and have the Automation Broker use it. You can also create your own broker without needing to write a ton of code. See https://github.com/jmrodri/samplebroker 
depends-on https://github.com/automationbroker/bundle-lib/pull/72
=> Allow Automation Broker to be useful when used as a dependency

pkg/handler/handler.go
Deprovision requests that returned an "already in progress" response
were failing to return the relevant operation token. This ensures the
correct token is returned so the catalog can continue to track.
=> Bug 1550418 - Return op token on depro in progress

pkg/broker/broker.go
* changes log statements to make things more obvious what is happening.
=> Bug 1577144 - fixing logging so it is more clear

Gopkg.lock, Gopkg.toml, pkg/dao/crd/dao.go, pkg/dao/etcd/dao.go, vendor/github.com/automationbroker/bundle-lib/apb/types.go, vendor/github.com/automationbroker/bundle-lib/registries/adapters/partner_rhcc_adapter.go, vendor/github.com/automationbroker/bundle-lib/registries/adapters/partner_rhcc_adapter_test.go, vendor/github.com/automationbroker/bundle-lib/registries/registry.go
This makes the dao calls happen 1 at a time for a dao. Attempts to handle the case when two service instances are gotten with two bindings. both are deleted, but because we only remove each of one, and when we update we just set the value, we were adding back a binding.
Depends on https://github.com/automationbroker/bundle-lib/pull/80
=> Bug 1576728 - Fixes multiple requests to a CR

docs/config.md
Documents the partner registry adapter implementation
depends-on https://github.com/automationbroker/bundle-lib/pull/77
Trello:
https://trello.com/c/PUOWeaEl
=> add partner rhcc adapter documentation

.tito/releasers.conf, ansible-service-broker.spec
Update our RPM version for release `1.3.z` of the broker. Also, make sure our tito releasers file is pointing to 3.11, for when those branches exist.
=> Bump version for next release

pkg/broker/broker.go
I moved things around to group the creation of the params hash to be together.
=> Bug 1578319 - send _apb* parameters to unbind

pkg/broker/broker.go
Add the requested update parameter to the changed parameters when not found in the existing serviceinstance.
Fixes: #934
=> Add requested parameters when not in existing service instance

pkg/broker/broker.go, pkg/broker/job_state_subscriber.go
If the unbind fails we really want to let them know it failed because it
is probably something the APB developer needs to fix. But if the action
is non-existent we really need to prevent the multiple sandboxes.
If we can't find the action, there is no point in continuing.
marking job as SUCCEEDED but setting the message to be the actual error
string. This will only happen for the optional actions: bind & unbind.
Update isJobInProgress to take a string to allow the proper ID to be
passed in.
=> Bug 1583064 - missing action causes many sandboxes

.travis.yml
Want to make it possible for travis to run against Pull Requests, as well as on merges to our master + release branches. This + some travis configuration should allow that.
=> Travis should run only for master/release branches

docs/config.md
Reading the raw markdown text files was difficult because the tables were just jammed together. Adding extra whitespace makes it easier to read in raw format. The web rendering is identical.
Alternatively, you could do `pandoc config.md | lynx -stdin` and see the html rendered but that wasn't ideal each time.
=> reformat tables to be readable without rendering

pkg/app/app.go, pkg/broker/broker_test.go
the namespace for the broker can change. So ensure it is passed through to the runtime package at startup.
While testing some state changes, I noticed state was not being saved this was due to the fact it was expecting to save to the ns ansible-service-broker.
While running make check I noticed that several tests were failing due to compilation errors so I fixed these also.
=> Pass in namespace to runtime

test/bind.sh, test/bootstrap.sh, test/catalog.sh, test/deprovision.sh, test/getbind.sh, test/getinstance.sh, test/last_operation.sh, test/last_operation_bind.sh, test/provision.sh, test/unbind.sh
Add hostname variable to test scripts and change the url
- Add hostname variable in all test scripts and take it as the last command line argument
- Change the url to reflect new changes
=> Add hostname to test scripts

.gitignore, CONTRIBUTING.md, Makefile, build/Dockerfile-canary, build/Dockerfile-localdev, build/dev-entrypoint.sh, scripts/clean_debug_env.sh, scripts/prep_debug_env.sh
Change to help with the development process from a contributor point of view. Allows building of a remotely debuggable image so a debugger can be attached when needed.
Feel free to close this if it is seen to have no value but I found it useful when working on recent issues so thought I would share.
On a side note the docs to run a local broker did not work for me on OSx on either `minishift` or `oc cluster up` but perhaps I'm missing something (broker started but errors out).
=> Support building a debuggable image for development

docs/config.md, pkg/app/app.go
This enables testing the broker with stage registries that use a self-signed CA. It could also be useful for other scenarios. It is a companion PR to https://github.com/automationbroker/bundle-lib/pull/98
- surfaces a setting that exposes a feature of bundle-lib that can skip TLS cert verification
=> adds docs and plumbing for the skip_verify_tls setting on the rhcc adapter

apb/tasks/main.yml, apb/templates/broker-access.clusterrole.yaml, apb/templates/broker-client.clusterrolebinding.yaml, apb/templates/broker.servicecatalog.yaml, apb/vars/main.yaml
Adds a switch that will install the broker as a namespaced broker into the `broker_namespace` specified. This will only function if the catalog running has the feature gate `NamespacedServiceBroker` set to true.
=> Add ns broker support to the broker's apb

docs/config.md
Update the documentation for ASB configuration: add `tag` among the registry configuration fields.
- Minor ASB documentation update
=> Add tag to the ASB registry configuration doc

pkg/broker/util.go, pkg/broker/util_test.go
I opened this issue a couple of days ago: https://github.com/openshift/origin-web-console/issues/2985 because the `update` form definition object was always empty so I made this tiny change into the service broker to include all updatable fields into the service instance object.
I am sending this PR to ask for feedback about this change, if this makes sense at all.
- Fills the update form definition object up with  a list of updatable fields (if any)
This PR breaks the service instance ui (when listing read-only parameters) which will need a change as well if this change makes any sense.
=> update obj form definition

docs/README.md, docs/namespaced-brokers.md
Adds namespaced broker documentation in the context of the automation broker.
=> Add namespaced broker docs

apb/defaults/main.yml, apb/tasks/main.yml, apb/templates/broker.configmap.yaml, docs/config.md
Update the Broker's APB to support configuring the Ansible Galaxy registry adapter as well as our config doc.
=> Add galaxy adapter

Gopkg.lock, Gopkg.toml, apb/defaults/main.yml, vendor/github.com/automationbroker/bundle-lib/bundle/types.go, vendor/github.com/automationbroker/bundle-lib/registries/adapters/adapter.go, vendor/github.com/automationbroker/bundle-lib/registries/adapters/dockerhub_adapter.go, vendor/github.com/automationbroker/bundle-lib/registries/adapters/galaxy_adapter.go, vendor/github.com/automationbroker/bundle-lib/registries/adapters/quay_adapter.go, vendor/github.com/automationbroker/bundle-lib/registries/registry.go
This PR updates the broker to pass the Galaxy URL to the APB at runtime when acting on `*serviceclasses` that come from Galaxy. This is important because the APB needs this information in order to properly install the role from Galaxy.
=> Update galaxy-adapter to include galaxy URL

pkg/app/app.go
The broker log outputs the newline code in the logs which is not what
was intended. This PR removes the \n from the log string.
time="2018-08-02T17:09:26Z" level=info msg="Ansible Service Broker Version: 1.3.6\n"
=> remove newline from version log

cmd/broker/main.go
calling flag.CommandLine.Parse prevents "ERROR: logging before flag.Parse:
errors from glog (used by k8s' apiserver package) see
https://github.com/kubernetes/kubernetes/issues/17162#issuecomment-225596212
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1577797
=> Bug 1577797 - call flag...Parse to prevent logging error

pkg/broker/broker.go, pkg/handler/handler.go
Changes updates to always run, regardless of whether parameters have changed.
This behavior change is in response to BZ 1583503. We previously blindly assumed that if the parameters have not changed since the last request that the last request succeeded, which we simply cannot guarantee.
Since David has done work to ensure our APB updates are idempotent it should be acceptable to rerun updates without changes. But it will probably make it a hard requirement rather than a polite suggestion that update tasks be idempotent.
fixes BZ 1583503
=> Bug 1583503 Always run updates

apb/tasks/generate_certificate.yaml, apb/templates/broker-access.clusterrole.yaml, apb/templates/broker.configmap.yaml, apb/templates/broker.service.yaml, apb/templates/broker.servicecatalog.yaml, docs/config.md, pkg/app/app.go, pkg/broker/broker.go
A lot of the time, the configurability of the `cluster_url` simply causes trouble. This removes that but there are definitely considerations for:
1. python apb tool - https://github.com/ansibleplaybookbundle/ansible-playbook-bundle
1. the other apb tool - https://github.com/automationbroker/apb
1. ansible installer - https://github.com/openshift/openshift-ansible/blob/master/roles/ansible_service_broker/tasks/install.yml#L239
1. Documentation - https://github.com/openshift/openshift-docs/pull/11145
=> Standardize broker endpoints

pkg/broker/broker.go
A regression was introduced that caused us not to handle the case when
the extracted credentials were not found in the switch statement. It
used to work because we were doing the client.IsNotFoundError for both
checks. We switched one to checking for an exact error:
ErrExtractedCredentialsNotFound but didn't update the switch statement.
=> Bug 1615723 - check for not found ext creds

test/bind.sh, test/bootstrap.sh, test/catalog.sh, test/deprovision.sh, test/getbind.sh, test/getinstance.sh, test/last_operation.sh, test/last_operation_bind.sh, test/provision.sh, test/unbind.sh
PR #1029 standardized the urls to be `osb/` so this updates the test scripts to use the same paths.
=> use the new osb prefix

apb/defaults/main.yml, apb/tasks/dao_crd.yaml, apb/tasks/main.yml
With namespaced brokers now supported, it's likely that there will be multiple brokers deployed simultaneously into a cluster, and there are a set of resources that are potentially shared between all of them. If a cluster admin decides to deprovision one of the brokers with the APB, we want the default behavior to prevent breaking other brokers by pulling down a resource that they depend on. The cluster admin can switch on the new var `broker_destroy_shared_resources` and rerun deprovision to easily clean these up when they are sure it will not interfere with others.
=> Default to NOT deleting shared broker resources

apb/defaults/main.yml, apb/tasks/main.yml
Guards the APB against deprovisioning brokers that have outstanding instances, but adds a switch to allow for a deprovision override.
=> Prevent deprovision of brokers with instances

apb/defaults/main.yml
This is intended to help mitigate https://bugzilla.redhat.com/show_bug.cgi?id=1618547 in 3.11.
=> Disable keeping namespace on error in ASB

ansible-service-broker.spec, downstream.patch
The operator refactoring moved some paths around (`apb` -> `ansible_role`) and that seems to have broken copr.
- Fix paths in .spec file
=> Fix RPM build

.tito/releasers.conf
The release-1.1 broker image built from source is excessively large as well. I want to make sure the upstream rpm is up to date and rebuild that image as well.
=> Fix 1.1 copr releaser

ansible_role/apb/Dockerfile-v3.10
We need to downgrade apb-base-scripts until https://github.com/openshift/origin/pull/20584 is merged and there is a new 3.10 oc.
=> Fix v3.10 automation-broker-apb Dockerfile

ansible_role/apb/Dockerfile-canary, ansible_role/apb/Dockerfile-nightly
Update the canary apb to use the canary apb-base and rename it to be clear which image it is used for.
=> Fix canary, use same tag for canary/nightly broker and apb's

templates/deploy-ansible-service-broker.template.yaml
Fix the default Broker URL Prefix for the 1.3/3.11 deploy template.
=> Fix deploy template default value for Broker URL

ansible_role/operator/Dockerfile
latest is stuck at v3.10 until a new v3.10 oc binary is released (if ever).
Using latest for the image therefore causes a mismatch between the nonResourceUrl's configured in the client access cluster role (/osb) and where the broker image is serving (/ansible-service-broker). Using v3.11 for now should prevent this from happening.
=> Use 3.11 instead of latest for ansible-service-broker image

ansible_role/playbooks/operator.yml
This should make it so that the broker_name and broker_namespace are set by the Ansible Operator passing in the `meta` object as extravars.
=> Operator should use meta from AO

ansible_role/operator/Dockerfile
I am working on submitting a PR to add our operators to the Openshift Prow CI.
https://github.com/openshift/release/pull/2098/files
I don't see that there is a way to submit build-args in the config to build from a Dockerfile. Given we need OLM_MANAGED is required for the operator to work with OLM and that we're not really aware of a real case where someone would use the operator without OLM I think it makes sense to change this to true.
=> Set OLM_MANAGED to true by default in the operator Dockerfile

ansible-service-broker.spec
A bad test package with a much higher version number was released downstream. We need to add an epoch to take precedence over it.
=> Add epoch to rpm spec

ansible-service-broker.spec
A bad test package with a much higher version number was released downstream. We need to add an epoch to take precedence over it.
=> Add epoch 1.3

ansible_role/tasks/main.yml, ansible_role/templates/broker-service-ca-bundle.configmap.yaml, ansible_role/templates/broker.servicecatalog.yaml
- Make changes to ansible role so that broker can be deployed onto OpenShift 4.0 and `clusterservicebroker` resource will contain correct `caBundle: <blob>` section which is required for successful communication with the broker.
A build of this is currently pushed to _docker.io/djwhatle/asb-operator:4.0-svcat-cert_
- Create 4.0 cluster including OLM
- Create `kube-service-catalog` namespace
- Create Service Catalog subscription [link](https://github.com/djwhatle/stuff/blob/master/olm-svcat-brokers-testing/svcat-subscription.yaml)
- Create osb-operators configmap [link](https://github.com/djwhatle/stuff/blob/master/olm-svcat-brokers-testing/osb-operators.configmap.upstream.4.0-fixed.yaml) (references my custom image above)
- Create osb-operators catalogsource …
=> Fix caBundle population for 4.0 deploys

ansible_role/tasks/main.yml
- Add check for ca-bundle configmap existence before overwriting
- Avoid contention between ASB operator and cert-signer operator in modifying the ca-bundle configmap
A build of this is currently pushed to _docker.io/djwhatle/asb-operator:4.0-svcat-cert_
Went with a relatively simplistic implementation of this check so that we can get it in and start testing. I don't think we lose significant value with this approach vs. a smarter approach that would verify the integrity of the structure in the configmap.
- Create 4.0 cluster including OLM
- Create `kube-service-catalog` namespace
- Create Service Catalog subscription [link](https://github.com/djwhatle/stuff/blob/master/olm-svcat-brokers-testing/svcat-subscription.yaml)
- Create osb-operators configmap …
=> Check if ca-bundle configmap already exists to avoid contention with cert-signer operator

ansible_role/playbooks/operator.yml
The operator playbook will now enforce `broker_name`, `broker_namespace`, and `broker_image` to be defined with `broker_image` being captured from the operator's environment.
=> Update operator playbook to use IMAGE from environment

ansible_role/operator/Dockerfile
Files are always added to the container owned as root.
When the users group is properly set the commands aren't run with the root group and fail. The upstream image is running commands as ansible-operator:root rather than ansible-operator:ansible-operator so it doesn't see this.
=> Fix downstream container builds

ansible_role/Dockerfile.operator.ocp
My understanding is the Dockerfile for downstream OCP builds must exist in the build context directory. Essentially what is run is, "docker build -f $DIR/$DOCKERFILE $DIR".
As far as I know it can be a link. If for some reason it can't I can PR a swap of the file and link.
=> Add Dockerfile link to prepare for automated downstream builds

ansible_role/operator/Dockerfile, ansible_role/operator/crd.yaml
Update to use latest Ansible Operator base image, and add required `subresources` field to CRD.
=> Update operator Dockerfile to use AO master, add subresource in CRD

ansible_role/defaults/main.yml, ansible_role/playbooks/test.yml, ansible_role/tasks/generate_certificate.yml, ansible_role/templates/broker-redirector.route.yaml, ansible_role/templates/broker.deployment.yaml, ansible_role/templates/broker.route.yaml, ansible_role/templates/broker.service.yaml, ansible_role/templates/broker.servicecatalog.yaml
Updates operator resource names to maintain 3.11 backwards compatibility. Our current defaults are blocking QE testing https://bugzilla.redhat.com/show_bug.cgi?id=1664506
- Use `openshift-ansible-service-broker` ns
- Use `ansible-service-broker` broker_name
- Use `asb` for service & route names
Related: https://github.com/fusor/catbrokers4/pull/7
=> Bug 1664506 - Update operator resource names to maintain 3.11 backwards compatibility

operator/deploy/olm-catalog/0.1.0/automationbroker.crd.yaml, operator/deploy/olm-catalog/0.1.0/automationbrokeroperator.v0.1.0.clusterserviceversion.yaml, operator/roles/ansible-service-broker/defaults/main.yml, operator/roles/ansible-service-broker/tasks/main.yml, operator/roles/ansible-service-broker/tasks/validate_present.yml, operator/roles/ansible-service-broker/templates/broker-client.clusterrole.yaml.j2, operator/roles/ansible-service-broker/templates/broker-config.configmap.yaml.j2, operator/roles/ansible-service-broker/templates/broker.automationbroker.yaml.j2, operator/roles/ansible-service-broker/templates/broker.clusterrole.yaml.j2, operator/roles/ansible-service-broker/templates/broker.clusterrolebinding.yaml.j2, operator/watches.yaml
This PR continues #1166, adding requirements for deployment via OLM. The key differences between this and the previous operator is:
* APB support has been dropped, in favor of a role that is specifically designed for ansible operator.
* The operator's ansible is responsible for provisioning the application's SA and RBAC, rather than delegating this to OLM.
* The public interface has been simplified with the expectation that users will express their configuration via a limited set of values in their CRs. Legacy operating modes such as basic auth and an etcd based dao have been deprecated.
=> Add OLM support to new operator

Makefile, operator/roles/ansible-service-broker/handlers/main.yml, operator/roles/ansible-service-broker/tasks/main.yml, operator/roles/ansible-service-broker/tasks/validate_absent.yml, operator/roles/ansible-service-broker/templates/broker.servicecatalog.yaml.j2
Works around an issue with the k8s lookup plugin not loading
auth from the environment, causing ssl failures
Also switches over the Makefile to build from the new operator
location
=> Explicitly set kubeconfig on lookups

operator/deploy/olm-catalog/0.2.0/bundlebindings.crd.yaml
Fixes typo in the bundlebinding singular name
=> bug 1684420: fixing name in the bundlebinding CRD

operator/roles/ansible-service-broker/tasks/main.yml
The operator needs admin permissions. When the operator is not run with admin permissions, the logs on operator pod should show a proper error message
=> Update operator/role, show error message on misconfigured RBAC

operator/build/olm-testing.Dockerfile
This adds a docker file, that will allow you to use the downstream CSV for an OLM install while changing the images that it creates. You will need to create a new container image and deploy this into the cluster. 
To use this Dockerfile:
1. create a new image from the `operator` directory. Exmaple:
`$ docker build -t quay.io/shawn_hurley/testing-downstream-catalog-source -f build/olm-testing.Dockerfile --build-arg operator_name=quay.io/shawn_hurley/abo:v4.0 --build-arg broker_name=quay.io/shawn_hurley/ab:v4.0 .`
2. Run this image as a catalog source by creating this resource:
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: abo-registry
namespace: openshift-operator-lifecycle-manager
spec:
sourceType: grpc
image: …
```
=> adding OLM testing file

pkg/app/app.go, pkg/registries/adapters/adapter.go, pkg/registries/adapters/oauth/client.go, pkg/registries/adapters/oauth/client_test.go, pkg/registries/adapters/rhcc_adapter.go, pkg/registries/adapters/rhcc_adapter_test.go, pkg/registries/registry.go
* fix debug statement
* add version log string
* copy the skip_verify_tls setting to the reg config
* pass client around so we can skip tls on image get
=> Bug 1678158 - backport oauth2 support to rhcc

operator/roles/ansible-service-broker/defaults/main.yml
The default sandbox should be edit for all ASB's created by an operator.
=> Bug 1693953 - Setting correct default for ASBs that are deployed with the operator.

operator/roles/ansible-service-broker/defaults/main.yml, operator/roles/ansible-service-broker/tasks/main.yml, operator/roles/ansible-service-broker/templates/broker.service-monitor.yaml.j2, operator/roles/ansible-service-broker/templates/prometheus.role.yaml.j2, operator/roles/ansible-service-broker/templates/prometheus.role_binding.yaml.j2
This makes the Ansible Service Broker Operator deploy a ServiceMonitor for the Ansible Service Broker, allowing it to expose metrics to prometheus.
https://bugzilla.redhat.com/show_bug.cgi?id=1692281
=> Bug 1692281 - operator should deploy a service-monitor

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1.0/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml, operator/molecule/cluster-olm/e2e-olm.sh, operator/molecule/cluster-olm/molecule.yml, operator/molecule/cluster-olm/playbook.yml, operator/molecule/cluster-olm/prepare.yml, operator/molecule/cluster/prepare.yml
Adding ability to CI test installation of the operator with OLM
- Create CSV with IMAGE_FORMAT
- Create olm resources to deploy the broker in the correct namespace. 
-
**note**: Want to move from template to lineinfile module so we only need a single CSV.
=> Adding ability to deploy ASB with OLM and csv to test.

operator/roles/ansible-service-broker/tasks/main.yml, operator/roles/ansible-service-broker/templates/broker.monitor-role.yaml.j2, operator/roles/ansible-service-broker/templates/broker.monitor-rolebinding.yaml.j2
Adding permissions for the service monitor that is created so that it can be used without intervention.
- add service monitor's RBAC permissions
=> Bug 1692281 - Adding service monitor permissions if monitoring is installed

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
Adding art.yaml file to allow for art to update the csv and package files on builds so that everything is built with the correct versions in the correct places.
=> Bug 1721161: cherry-pick art.yaml to 4.1 release

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
Typo in art.yaml. The file name was not updated to a minor version and therefore need to change art.yaml to reflect the actual name of the file.
=> Bug 1721161: Fix typo art.yaml

Gopkg.lock, Gopkg.toml, vendor/github.com/automationbroker/bundle-lib/clients/kubernetes.go, vendor/github.com/automationbroker/bundle-lib/registries/adapters/apiv2_adapter.go, vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client.go
When using APIV2 registries, if we hit the pagination sequence, the registry code would fail to get the next page and thus not return any images to the broker. If the set of images on the registry is less than the page size, things worked or if the images were listed individually in the configuration.
Fixes: BZ 1723422
=> Bug 1723422 - fix pagination url, bump bundle-lib

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/openshiftansibleservicebroker.v4.2.0.clusterserviceversion.yaml, operator/roles/ansible-service-broker/templates/broker.deployment.yaml.j2
OLM will be setting these variables on operator deployments and we need to pass them through to deployments created by the operator
=> Pass *_PROXY envvars on to ASB deployment

docs/usecases.md
The diagrams have an additional actor due to different writing of `Ansible Service Broker`. I have not seen a guide to regenerate the diagram in the contributing section. So this is currently missing.
=> fix Etherpad and Bindable database service diagrams

operator/roles/ansible-service-broker/tasks/main.yml, operator/roles/ansible-service-broker/tasks/trusted_ca_bundle.yml, operator/roles/ansible-service-broker/templates/broker.deployment.yaml.j2
Properly injects the trusted CA bundle into the ASB deployment managed by the operator. It's a requirement to support this.
=> Add logic to inject the trusted CA bundle

Gopkg.lock, Gopkg.toml, vendor/github.com/automationbroker/bundle-lib/registries/adapters/apiv2_adapter.go, vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client.go, vendor/github.com/automationbroker/bundle-lib/registries/registry.go
The registry-proxy GET /v2 returns a WWW-Authenticate header with only a
realm: .../v2/auth the APIV2Adapter simply gets a token for /v2/auth
which is not valid for registry-proxy which seems to require a scoped
token.
In this PR, we added a new RegistryProxyAdapter that now requires the
apbs to be listed in the configuration. For each of those images listed,
we will add them to the scope when we ask for the token. This allows the
broker access to fetch the apb images.
Also, added a test to ensure registry proxy errors when no images are defined
and added a unit test for getTokenWithScope.
=> Bug 1763005 - add registry-proxy support, bump bundle-lib

build/custom-ci-build-root.Dockerfile
fix ci: master branch custom build image should still using python 2
Fix the build with python. We shoud not upgrade it since the https://github.com/openshift/ocp-release-operator-sdk/blob/master/release/ansible/Dockerfile#L21 still using python2. The current molecule impl ocp-release-operator-sdk will not work with python3. It is facing the encoding issue. 
```
2020/03/25 17:26:07 Container setup in pod operator-molecule-e2e completed successfully
secret/support created
Traceback (most recent call last):
File "/usr/local/bin/molecule", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 760, in main
_verify_python3_env() …
```
=> fix ci: master branch custom build image should still using python 2
