Makefile
cmd/broker/main.go
cmd/mock-registry/ansibleapps.yaml
cmd/mock-registry/mock_registry.go
cmd/mock-registry/run.sh
glide.lock
glide.yaml
pkg/ansibleapp/dev_registry.go
pkg/ansibleapp/registry.go
pkg/ansibleapp/rhcc_registry.go
pkg/app/app.go
pkg/dao/dao.go

* Implemented some basic dao features for talking with etcd
* Filled out a mock-registry as a separate binary so we have something to pull data from in a real way.

DAO & Mock Registry

---

.codeclimate.yml
pkg/ansibleapp/dev_registry.go
pkg/ansibleapp/types_test.go
pkg/app/args.go
pkg/app/config.go
pkg/dao/dao.go

* Update codeclimate with desired ignores
* Fix legitimate complaints

Codeclimate polish

---

cmd/mock-registry/ansibleapps.yaml
pkg/ansibleapp/provision.go
pkg/ansibleapp/types.go
pkg/ansibleapp/types_test.go
pkg/broker/broker.go
pkg/broker/types.go
pkg/broker/util.go
pkg/dao/dao.go
test/catalog.sh
test/provision.sh

* `broker::Provision` implementation
* `ServiceInstance` type for instance bookkeeping
* Dao support for ServiceInstances
* Made {Dump,Load}JSON methods more generic for reuse across model types

Provision support

---

cmd/mock-registry/ansibleapps.yaml
pkg/ansibleapp/client.go
pkg/ansibleapp/deprovision.go
pkg/ansibleapp/hack.go
pkg/ansibleapp/provision.go
pkg/broker/broker.go
test/bind.sh
test/bootstrap.sh
test/catalog.sh
test/deprovision.sh
test/provision.sh
test/unbind.sh

* Pushed the details of actually running ansibleapps into some generic abstractions
* Point test scripts to vagrant env by default
* Point mock registry data to correct docker hub org
* Use spec conformant responses

Implement Deprovision Stub

---

.gitignore
Makefile
README.md
etc/ex.dev.config.yaml
etc/ex.prod.config.yaml
glide.lock
glide.yaml
pkg/ansibleapp/client.go
pkg/ansibleapp/dev_registry.go
pkg/ansibleapp/dockerhub_registry.go
pkg/ansibleapp/hack.go
pkg/ansibleapp/registry.go
pkg/ansibleapp/types.go
pkg/app/app.go
pkg/app/args.go
pkg/broker/util.go
scripts/get_images_for_org.sh
scripts/runbroker.sh

Registry adapter to support bootstrapping the broker from dockerhub.

DockerHubRegistry

---

Makefile

* Prevents duplicate symbol error

Remove docker/vendor directory before compilation

---

.gitignore
scripts/asbcli/asbcli
scripts/asbcli/requirements.txt

* Acts as a client+ServiceCatalog for interactively driving an AnsibleServiceBroker

asbcli tool

---

scripts/asbcli/asbcli

flake8 said ```_header``` was unused, but I think it was to save the existing header values update them then replace with the modified set. If not, I can fix it.

fix flake8, _headers wasn't doing anything

---

README.md
docs/design.md

* Also add bit about config file setup to main README.md

Update docs with registry information

---

docker/ansible-service-broker
docker/entrypoint.sh
docker/oc-login.sh
etc/ex.dev.config.yaml
etc/ex.dockerimg.config.yaml
etc/ex.prod.config.yaml
pkg/ansibleapp/client.go
pkg/ansibleapp/hack.go
pkg/ansibleapp/provision.go
pkg/app/app.go
pkg/app/config.go
pkg/broker/broker.go
scripts/asbcli/README.md
scripts/asbcli/asbcli

* Container assets
* Updated confs
* Properly parameterize targeted openshift cluster
* asbcli support for deploying broker
**NOTE:** This is a breaking change for asbcli, uses cli interface outlined in README.md

Broker ansibleapp

---

.gitignore
Dockerfile
README.md
ansible/ansible.cfg
ansible/container.yml
ansible/main.yml
ansible/meta.yml
ansible/requirements.txt
ansible/requirements.yml
ansible/roles/ansible-service-broker-openshift/.travis.yml
ansible/roles/ansible-service-broker-openshift/README
ansible/roles/ansible-service-broker-openshift/defaults/main.yml
ansible/roles/ansible-service-broker-openshift/library/oso_deployment.py
ansible/roles/ansible-service-broker-openshift/library/oso_pvc.py
ansible/roles/ansible-service-broker-openshift/library/oso_route.py
ansible/roles/ansible-service-broker-openshift/library/oso_service.py
ansible/roles/ansible-service-broker-openshift/meta/main.yml
ansible/roles/ansible-service-broker-openshift/tasks/main.yml
ansible/roles/ansible-service-broker-openshift/test/.travis.yml
ansible/roles/ansible-service-broker-openshift/test/test.yml
ansible/shipit-openshift.yml
ansibleapp.yml
ansibleapp/actions/provision.yaml
pkg/app/app.go
pkg/app/args.go

Moving the ansibleapp / Docker files here instead of ansibleapp-library so we can make sure new images are built for dockerhub on tagged updates of this repo.
* Also added a "--version" option to the command line so it will line up with tags.

Move ansibleapp files to service broker repo

---

pkg/broker/broker_test.go
pkg/broker/util_test.go

Test some of the files in broker package: util.go and broker.go.

Add tests to broker pkg

---

pkg/fusortest/util.go
pkg/handler/handler.go
pkg/handler/handler_test.go
pkg/handler/io_test.go

Refactored the handler to be more testable by allowing you to pass in a map[string]string as a third argument.

Increase test coverage

---

docs/bind-data-transmission.md

The goal of this doc is to explain the different options
for passing data between the APB and the Broker.

Bind-data-transmisson doc

---

docs/bind-data-transmission.md

Found some new information regarding output on exit.

Update the output-on-exit section

---

pkg/apb/bind.go
pkg/apb/bind_test.go
pkg/apb/client.go
pkg/apb/dockerhub_registry.go
pkg/apb/ext_creds.go
pkg/apb/ext_creds_test.go
pkg/apb/provision.go
pkg/apb/types.go
pkg/apb/types_test.go
pkg/app/app.go
pkg/broker/broker.go
pkg/dao/dao.go

Bind tests are all broken, need updating before merge.

ExtractedCredentials Refactor

---

pkg/apb/client.go

Refreshes the oc credentials to prevent expiry before attempting to run an apb.

Add refresh token logic

---

Makefile

Introductory make target to build asb images. It's not perfect, but it seems to work and I don't have to worry about missing a step.

add ability to build images

---

pkg/apb/ext_creds.go

* Fixes possible seg fault
* Patch will continue to retry for errors its not aware of and dump
debug information

Fix broker retry logic for unknown errors

---

pkg/broker/broker.go
scripts/asbcli/asbcli

Tested locally with pydemo/postgres-demo-apb and it executes the bind request immediately, worked okay for me. Needs more eyes on it before merge.

NOOP apb on bind

---

glide.lock
pkg/app/app.go
pkg/dao/dao.go

Validate we are connected to endpoints before we start the broker.

Endpoint validation

---

pkg/apb/dockerhub_registry.go

https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices

change how we declare empty slides

---

Makefile
glide.lock

We need to update the glide.lock file to reflect the recent changes to glide.yaml.
Partially fixes #100

Update glide.lock file

---

Makefile
build/Dockerfile
build/config.yaml
etc/ex.dev.config.yaml
scripts/deploy.sh
templates/broker-deployment_template.yaml

A few changes to the Dockerfile, templates, and tooling around it.

Template and tool updates

---

ansible-service-broker-all.yaml

oc create -f ansible-service-broker-all.yaml

Add a single template that can deploy the broker

---

ansible-service-broker-all.yaml
build/entrypoint.sh
pkg/apb/client.go
pkg/apb/ext_creds.go
pkg/apb/hack.go
pkg/app/config.go
pkg/broker/broker.go
pkg/broker/util.go
templates/broker-deployment_template.yaml

Remove openshift_{target|user|password}.
Still trying to figure out how to test

log in with serviceaccount certs and token

---

pkg/broker/broker.go
pkg/handler/handler.go

Deprovison spec compliance

---

Makefile
README.md
cmd/mock-registry/run.sh
scripts/runbroker.sh
scripts/travis.sh

This needs to be rebased on master once https://github.com/openshift/ansible-service-broker/pull/148 is merged.

Fix makefile

---

extras/ansible-service-broker.spec
extras/ansible-service-broker.te

Needs to be rebased after everything else that touches the rpm spec gets merged

add selinux policy and update rpm spec to build the sub package

---

Makefile
build/Dockerfile
build/Dockerfile-src
build/entrypoint.sh

Allow ansible-service-broker container to run with an arbitrary user id
Closes #142

Run as arbitrary user

---

pkg/apb/bind.go
pkg/apb/client.go
pkg/apb/deprovision.go
pkg/apb/provision.go
pkg/apb/types.go
pkg/apb/unbind.go
pkg/broker/broker.go
pkg/broker/broker_test.go
pkg/broker/deprovision_job.go
pkg/broker/provision_job.go
pkg/broker/types.go
pkg/dao/dao.go
pkg/handler/handler.go
pkg/handler/handler_test.go

Haven't had a chance to test this yet, hoping to do that tomorrow morning once the big PRs get merged.
thanks to @shawn-hurley for the pair programming session to get this done

Implement deprovision and unbind

---

.travis.yml
pkg/broker/util.go
scripts/travis.sh

* add vet and golint. Vet will fail build.
Fixes #162.

162: show errors during failed format runs

---

scripts/prep_local_devel_env.sh

Was setting off all kinds of alarms in my vim :)

Strip line ending whitespace

---

build/Dockerfile-src
build/broker-config.yaml.example
build/entrypoint.sh
templates/deploy-ansible-service-broker.template.yaml

rather than create one with sed based on environment variables

Expect a config file to be mounted 

---

pkg/broker/broker.go
pkg/dao/dao.go

* Bootstrap should clear out the specs before completing the bootstrap

1463798 - Fix stale APBs present in ASB after bootstrap

---

pkg/broker/broker.go
pkg/handler/handler.go
pkg/handler/handler_test.go

This PR is needed by https://github.com/fusor/ansible-playbook-bundle/pull/58

Dev remove spec

---

pkg/apb/client.go

We don't need to pass in environment vars anymore
because of service accounts. We're always running the apb
incluster so oc login will use the service account to login.
Partially-fixes #196

Cleanup local pod split

---

pkg/broker/util.go
pkg/broker/util_test.go

201 - remove ProjectRoot

---

build/Dockerfile

1467852 - add ENV HOME to Dockerfile

Fix BZ1467852 add ENV HOME to Dockerfile (#263)

---

pkg/apb/provision.go

Forward port of fix from release-0.9 #273

1470860 - Remove broker project creation

---

scripts/asbcli/asbcli
scripts/asbcli/pod-preset.yaml
scripts/asbcli/secret.yaml

I did a little hacking on asbcli so I figured I'd share this.

Asbcli bind

---

templates/deploy-ansible-service-broker.template.yaml

I needed to make this change so the default values are friendlier to use.
Tested in conjunction with:
https://gist.github.com/jwmatthews/3c8a2844970cb350d43d91d37470e7d6

Updated template default values

---

docs/specs/Broker-CI.md

Add some more information to the broker-ci spec.

Update the broker-ci spec to include jenkins and travis

---

README.md
scripts/prep_local_devel_env.sh

Removes jq calls from development scripting

Remove usage of jq dependency

---

docs/specs/bind-unbind-workflow.md

Detailing the responsibility of the broker and APB to complete the new workflow.

[Proposal]: New Bind and Unbind Workflow

---

docs/specs/spec-template.md

The spec template will be a guide on how to create a spec.

Create a spec template

---

CONTRIBUTING.md
docs/specs/spec-template.md

Add a contributing doc that mentions the PR and spec process.

Contributing doc

---

scripts/run_latest_build.sh

- reformatting the comments to be more readable in 80 character terminals.
none
none (tech debt)

reformat the comments to be readable.

---

scripts/broker-ci/postgresql.yaml

Fix the plan name in broker ci object

---

pkg/broker/broker.go
pkg/registries/adapters/adapter.go

- Fix NPE panic when trying to provision zero param plans
No
https://github.com/openshift/ansible-service-broker/issues/324

Zero param fix

---

pkg/broker/broker.go
pkg/broker/types.go
pkg/handler/handler.go

* Move to FQNames broke apb push. Need to make sure we ID them
correctly before they're inserted to etcd
* Some extra logging for visibility in the future

Update AddApb to use FQNames

---

pkg/apb/ext_creds.go
pkg/apb/ext_creds_test.go

- Fixes issue preventing broker from handling integer credentials
fixes #335

Accept ints from exported credentials

---

templates/deploy-ansible-service-broker.template.yaml

This PR fixes yaml errors when using characters in a password
- Use strings for config map

Updated deployment template to use string substitution when applicable

---

scripts/broker-ci/local-ci.sh

There are some cases where the pod preset isn't ready
after the sleep. Let's add some retry logic around it.
- Remove a sleep in the ci script

Retry pod preset check instead of sleeping

---

docs/ssl_tls.md

Update ssl doc

---

.tito/releasers.conf

Updates the Copr releasers for tito
Update the Copr releasers for tito
No
N/A

Update Copr Releasers

---

CONTRIBUTING.md
Makefile
OWNERS
README.md

- Rename `pre-flight` make target to `check`
- Update Contributing guide to give the steps for install pre-reqs and setting up the environment
- Add OWNERS file to make it easy to ID reviewers/approvers
fixes #319

Improve user facing documentation for broker

---

scripts/run_latest_build.sh

I was having trouble using the RC build, but the full release started up for me successfully with this change.

Update version to the release instead of RC

---

CONTRIBUTING.md
README.md

Provide a link to the ansible service broker's mailman page so someone
may subscribe to the list.

Point doc readers to subscribe to mailing list

---

docs/proposals/form-metadata.md

Proposal to support order and groups in the front end forms based on apb information.  Display type is free along for the ride.

UI form metadata proposal

---

docs/config.md

Adds documentation around configuration of the openshift registry. We currently have no documentation for it.
- Updated config.md

Added documentation update for openshift registry

---

pkg/apb/types.go
pkg/app/app.go
pkg/broker/broker.go
pkg/broker/types.go
pkg/handler/handler.go
pkg/handler/handler_test.go
pkg/handler/io.go
pkg/registries/adapters/adapter.go
pkg/registries/adapters/dockerhub_adapter.go
pkg/registries/registry.go

Simply cleaning up comments so they are `// `
depends-on PR #404

make comments consistent '// '

---

docs/proposals/configuration_changes.md

Proposals to determine how to we will change configuration values to make them easier to use.

Proposals to make configuration easier to use.

---

docs/proposals/ci-framework.md

Proposal: CI Framework

---

docs/README.md
docs/config.md
docs/secrets.md

Add docs for secrets

---

scripts/prep_local_devel_env.sh

This will set default values during the local run if they are not set in my vars. 
fixes #424

updating default values for configuration values needed.

---

.gitignore
templates/k8s-ansible-service-broker.yaml.j2
templates/k8s-template.py
templates/k8s-variables.yaml

Resurrect the Kubernetes template. The template will be consumed by catasb.
- Jinja2 k8s template
- Python script to render the template using variables in k8s-variables.yaml
https://github.com/fusor/catasb/pull/120

Kube template

---

docs/proposals/apb-remove-image-field.md

A proposal to remove the image field from the APB spec, including some
implementation details.

Remove image field from APB spec

---

scripts/asbcli/asbcli

Fixes asbcli provision. bind still seems busted, but with this we can at least provision with asbcli again.
Changes proposed in this pull requestfixes <issue_number>
- Fixes asbcli provision to actually work
- Adds prompt for plan to use
No
N/A

fix asbcli provision

---

templates/deploy-ansible-service-broker.template.yaml

Allows you to deploy the service broker with the CA Bundle defined
https://github.com/fusor/catasb/pull/140

adding ability to pass in the CA Bundle for ServiceBroker

---

docs/administration.md

Adding documentation for how to deploy the ansible service broker. 
https://github.com/openshift/ansible-service-broker/pull/428

first pass at administration documentation

---

scripts/broker-ci/setup.sh

dockerhub_org_name was changed to dockerhub_org.

The docker organization name was changed in catasb

---

scripts/broker-ci/local-ci.sh
scripts/broker-ci/setup.sh
scripts/deploy.sh
scripts/my_local_dev_vars.example

* Add 3.6 params to make deploy script
* Remove 3.6 params for gate script and use make deploy defaults
* Change ```DOCKERHUB_USERNAME``` to ```DOCKERHUB_USER```
* Change ```DOCKERHUB_PASSWORD``` to ```DOCKERHUB_PASS```

Some of the 3.6 & 3.7 gate changes are causing issues

---

scripts/deploy.sh

The gate showed a false positive on #434, this will fix it.

Pass in args to the deploy scripts

---

README.md
scripts/run_latest_build.sh

Make the run latest script run the latest origin (by default) while supporting `v3.6.0`.

Update run_latest_build w/ origin latest default

---

templates/deploy-ansible-service-broker.template.yaml

Bug 1498992 - ENABLE_BASIC_AUTH setting should default to false

---

scripts/broker-ci/local-ci.sh

Fix api auth for ci test

---

templates/deploy-ansible-service-broker.template.yaml

This PR adds liveness and readiness checks to the ASB template on the ASB pod.
- Adds liveness and readiness check on /healthz

Bug 1503233 - Add liveness and readiness checks to ASB dc

---

docs/administration.md
docs/auth.md
docs/config.md
docs/deployment.md
docs/proposals/bind-unbind-workflow.md
docs/proposals/configuration_changes.md
docs/proposals/form-metadata.md
docs/proposals/keeping-transient-pod-name-spaces-alive.md
docs/proposals/logging_update.md
docs/proposals/portable-service-assets.md
docs/proposals/updates-first-pass.md
docs/proposals/user-impersonation-proposal.md
etc/example-config.yaml
scripts/broker-ci/error.sh
scripts/broker-ci/local-ci.sh
templates/deploy-local-dev-changes.yaml

Annoying trailing spaces removed.

remove trailing spaces from supporting files

---

scripts/broker-ci/local-ci.sh
scripts/broker-ci/setup.sh
scripts/openshift/deploy.sh
scripts/travis.sh

Fix gate for Openshift 3.7

---

pkg/broker/broker.go

- Change update handling to remove bad params from the request and log warnings instead of erroring out the request
depends-on N/A
fixes: origin-web-console issue 2349

accept update with bad params and log warnings instead of erroring

---

docs/deployment.md
etc/example-config.yaml
scripts/my_local_dev_vars.example
scripts/openshift/deploy.sh
scripts/prep_local_devel_env.sh

These variable aren't required to be set any more.

Remove checks for DOCKER_USER and DOCKER_PASSWORD

---

templates/deploy-ansible-service-broker.template.yaml

setting default for `auto_escalate` to false.
Please see discussion on #503

setting default value for the deployment template.

---

docs/config.md
etc/example-config.yaml

Adds docs on how to configure local openshift adapter.
- Doc changes

Bug 1507111 - Update docs and example configs for local openshift adapter

---

ansible-service-broker.spec

simple release bump for next release

bump version for next release

---

pkg/broker/broker.go

Remove unused ocLogin function

---

templates/k8s-template.py

/bin/env doesn't work on ubuntu.

Change the python path to /usr/bin/env

---

pkg/broker/broker.go

Fix update
- Send the Method so it actually stops additional containers from launching.
depends-on No
fixes N/A

stop multiple update apb containers from launching

---

templates/deploy-local-dev-changes.yaml

The labels appear to be incorrect, but it's not clear that they were causing any particular incorrect behavior.

Fixes labels on asb Endpoint in local dev template

---

pkg/app/app.go

Need to use the correct version of the RBAC api
- Use the correct RBAC api
fixes #617

Bug 617 - fixing issue with versioning the rbac API.

---

.tito/releasers.conf

Simply update releasers for tito.

Add 3.8/3.9 releasers to tito

---

pkg/handler/handler_test.go

fixing handler tests in master branch

---

docs/config.md

Updates config.md to include using a secret/file for registry credentials.
- config.md

Update config doc to document storing creds in a secret

---

README.md
scripts/run_latest_build.sh

Makes the `run_latest_build.sh` a little nicer on macOS
- Add minishift documentation to the getting started section. 
- Quiet the errors from ip addr and grep commands for macOS
fixes #639

quiet errors related to docker0 address

---

pkg/apb/secrets.go
pkg/app/app.go

* Uses the new config array to read secrets from broker config

Bug 1534957 - Fix secret parameters regression

---

pkg/broker/broker.go
pkg/broker/deprovision_job.go

Removes dead ref on a DeprovisionJob

Remove unecessary dao ref from DeprovisionJob

---

.travis.yml
scripts/broker-ci/pv-setup.sh
scripts/broker-ci/setup-minikube.sh
scripts/run_latest_k8s_build.sh
scripts/travis.sh

To add k8s CI to other repos, we can't user relative paths. We need to use urls.
- Replace relative paths with urls

Make the k8s CI scripts consumable with curl

---

pkg/clients/openshift.go
pkg/handler/handler.go

Bug 1538732 - Adding ability for Subject Rules Review to do the correct check.

---

pkg/broker/broker.go
pkg/handler/handler.go
pkg/handler/handler_test.go

Previously it was incorrectly returning response code 200 when the operation
ran asynchronously.
fixes #701

Bug 1539757 - async unbind returns http 202

---

pkg/handler/handler.go

Backports #700 to the release branch.

Backport fall-through default for deprovision

---

pkg/auth/auth.go
pkg/auth/auth_test.go
pkg/auth/testdata/test-config.yaml

Added a test but it requires some directory to be installed on your desktop. I marked it as skip for now.

Bug 1541335 - fix auth config parsing

---

pkg/broker/broker.go
pkg/handler/handler.go

Bug 1540121 - Return 400 for bad update requests

---

.travis.yml
scripts/travis.sh

Perform the git diff check against HEAD^ because travis merges all commits into one commit at HEAD.  This will prevent release branches from always thinking the pull request is a doc change.

Travis merges commits so do a diff against HEAD^

---

pkg/broker/broker.go

* Noticed an oversight in the recent update validation fix.

Bug 1540121 - Remove redundant validation copy

---

pkg/handler/handler.go

Bug 1543029 - last_operation returns correct body with 410 response

---

templates/simple-broker-template.yaml

Escalate asb service account privileges for simple-broker-template
- Add more rules to asb-auth sa
Currently the up and running blog post is broken without this.

Include necessary roles for local_openshift reg in simple-broker-template

---

pkg/apb/executor.go
pkg/apb/types.go

Backporting proxy support for 3.7 pocs.

Add lowercase proxy vars to spawned pods

---

scripts/broker-ci/local-ci.sh
scripts/broker-ci/postgresql.yaml
scripts/travis.sh
templates/deploy-ansible-service-broker.template.yaml

Tring to fix issue with service binding not creating the secret or us not being able to find the secret.

Fix the CI for release-1.0

---

scripts/travis.sh

This should speed up the openshift job!

Remove upgrade from Ubuntu 14.0 to 16.04

---

scripts/broker-ci/setup-cluster.sh
templates/deploy-ansible-service-broker.template.yaml

Lock down templates and CI in this branch to the `release-1.1` broker + APB images.

Rel lockdown 1.1

---

docs/filtering_apbs.md
pkg/registries/filter.go
pkg/registries/filter_test.go
pkg/registries/testdata/empty_whitelist.yaml

backport of https://github.com/openshift/ansible-service-broker/pull/781
fixes: https://github.com/openshift/ansible-service-broker/issues/785

Bug 1549189 - Filter everything when whitelist is empty

---

README.md
docs/versioning.md

- Document broker's compatibility with APBs
- Document versioning and branching strategy

Document the Broker's versioning strategy

---

docs/proposals/apb-state-support.md

Cleanup the items I found while reviewing the APB State Proposal. I did not want to hold up the merge for Craig any longer. This is purely a grammar / spelling change.

Format nits

---

scripts/travis.sh

Add dep to travis

---

scripts/broker-ci/setup-cluster.sh
scripts/travis.sh

Using ```- include_tasks``` requires a newer version of ansible.
- Move to latest ansible version

Use the latest ansible version in travis scripts

---

scripts/openshift/deploy.sh
scripts/prep_local_devel_env.sh
scripts/run_latest_build.sh
scripts/run_latest_k8s_build.sh
templates/deploy-ansible-service-broker.template.yaml
templates/deploy-local-dev-changes.yaml
templates/k8s-ansible-service-broker.yaml.j2
templates/k8s-local-dev-changes.yaml

- remove all references to asb-etcd as we should no longer use that
- remove cert generation for asb-etcd from scripts 🎉

make CRD the defaults for all templates

---

Gopkg.lock
pkg/broker/broker.go
vendor/github.com/automationbroker/bundle-lib/.gitignore
vendor/github.com/automationbroker/bundle-lib/Makefile
vendor/github.com/automationbroker/bundle-lib/apb/types.go
vendor/github.com/automationbroker/bundle-lib/apb/types_test.go

This fixes bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1564542
- add an EnsureDefaults() to the parameters type that sets a default value for _apb_provision_creds var. More could be added in the future.
fixes https://github.com/openshift/ansible-service-broker/issues/818

Fix bug 1564542

---

docs/debugging.md

link broken - typo fixed

---

ansible-service-broker.spec
build/Dockerfile-canary

Actually build the migration command before trying to move it.

Build migration into canary image

---

Makefile

In honor of Project Spacewalk
https://github.com/spacewalkproject/spacewalk/blob/master/java/build.xml#L972-L977

Frustration release target

---

scripts/broker-ci/setup-catalog.sh

Make helm useful for travis until helm latest is functional.

Lock helm version for ci

---

apb/install.yaml

Simply add the install.yaml file to a known location in release branch.

Add install.yaml for release-1.0 broker

---

pkg/broker/broker.go
pkg/dao/crd/dao.go

* cleaned up a bunch of logging to use *f formatted form
* removed the SetState that causes update conflicts     
* cleaned up the dao logging to be more informative     
* changed formatting to be more narrow :)

Bug 1572129 - remove unnecessary SetState

---

CONTRIBUTING.md
README.md
docs/debugging.md
docs/design.md
docs/secrets.md
docs/service-bundle.md
pkg/app/app.go
pkg/auth/auth.go
pkg/broker/broker.go
pkg/broker/job_state_subscriber.go
pkg/broker/types.go
pkg/dao/crd/dao.go
pkg/dao/dao.go
pkg/dao/etcd/dao.go
pkg/dao/filters.go
pkg/fusortest/util.go
pkg/handler/handler.go
pkg/mock/dao.go
pkg/version/apbruntimeversion.go
pkg/version/apbversion.go
scripts/prep_local_devel_env.sh
templates/k8s-variables.yaml

Started off spell checking the log messages, and turned into something more.

Spell check a bunch of items

---

apb/install.yaml

Simply add the install.yaml file to a known location in release branch.

Add install.yaml for release-1.1 broker

---

scripts/run_latest_build.sh

fixes #943 
The issue was the template was coming from the latest branch which has breaking changes.
- change branch to get the template to release-1.1

lock the version of deploy template to correct branch

---

README.md

Update release dates in README

---

pkg/broker/broker.go

Bug 1578319 - send _apb* parameters to unbind

---

cmd/migration/main.go

Bug 1581580 - skip if bind instance does not have credentials

---

Gopkg.lock
vendor/github.com/automationbroker/bundle-lib/registries/adapters/openshift_adapter.go
vendor/github.com/automationbroker/bundle-lib/registries/adapters/openshift_adapter_test.go
vendor/github.com/automationbroker/bundle-lib/registries/adapters/partner_rhcc_adapter.go
vendor/github.com/automationbroker/bundle-lib/registries/registry.go
vendor/github.com/automationbroker/bundle-lib/registries/registry_test.go

Bring bugfixes from bundle-lib PRs into the broker:
1. https://github.com/automationbroker/bundle-lib/pull/82
1. https://github.com/automationbroker/bundle-lib/pull/90
1. https://github.com/automationbroker/bundle-lib/pull/85
1. https://github.com/automationbroker/bundle-lib/pull/96

Bump bundle lib to 0.1.8

---

.travis.yml
Makefile

`make ci` should not try to deploy the broker.

Make ci should not do deployment

---

.travis.yml

Move the deployment into a job stage (deploy) and run only on the main repo + specific branches (tags).

Fix deployment stage

---

.travis.yml
Makefile

Split branch and tag deploy steps.

Use travis_tag on tag builds

---

scripts/deploy.sh

`automation-broker` doesn't exist.

Fix default APB_IMAGE

---

ansible-service-broker.spec
apb/Dockerfile-latest
apb/Dockerfile-nightly

Create automation-broker-apb-role RPM

Broker apb rpm

---

apb/install.yaml
apb/tasks/main.yml
apb/vars/main.yaml
scripts/deploy.sh

Improve logging when wait_for_broker fails

---

apb/defaults/main.yml
apb/templates/broker.configmap.yaml
docs/config.md
pkg/app/app.go

required for quay adapter in [bundle-lib](https://github.com/automationbroker/bundle-lib/pull/75)
- added a `token` field in the `registry` section of the `broker_config`
depends-on [bundle-lib PR](https://github.com/automationbroker/bundle-lib/pull/75)
[Trello Card](https://trello.com/c/EgOcdkNp)

update for quay adapter

---

pkg/dao/crd/dao.go

When deprovisioning, we can't find a state because we have deleted it.
That is expected but our logs show an error log. This really isn't an
error in this scenario. In other scenarios it might be an error, but we
return the err to the caller which will either handle or log it
themselves. So keeping the message as a debug log is useful for us.
There are a couple other methods that were logging errors used by the
broker's recovery feature. The recovery feature handles the NotFound
error case, so we don't want to print errors during those scenarios. If
something other than NotFound is occurs, it would be helpful to log the
error.

Bug 1583587 - lower loglevel to debug, wrap others

---

apb/templates/broker.route.yaml

Add a timeout in the route annotation to stop issues like this: https://github.com/openshift/ansible-service-broker/issues/876
No
fixes 876

Add route timeout annotation

---

pkg/broker/job_state_subscriber_test.go

Because of the bug in the `Makefile` (see PR #1038) test failures were not being exposed when running the test-coverage target. This PR fixes the broken tests. We should then rebase the other PRs so they can get a clean bill of health.

Add mock for the call to DeleteExtractedCredential

---

docs/config.md

Doc update
- Include description for `skip_verify_tls`

Bug 1599522 - Include skip_verify_tls doc info for registries

---

pkg/app/app.go

Supports new bundle-lib metrics
depends-on https://github.com/automationbroker/bundle-lib/pull/161

Bug 1583049 - Add bundle-lib metrics registration

---

ansible-service-broker.spec

I had duplicated prep sections.

Fix broker rpm spec

---

downstream.patch

Fix downstream patch for capabilities check

---

apb/tasks/dao_crd.yaml
apb/tasks/main.yml
apb/templates/broker-auth.clusterrolebinding.yaml
apb/templates/broker-client.clusterrolebinding.yaml
apb/templates/broker.clusterrolebinding.yaml

* Accept quoted boolean for broker_destroy_shared_resources
* Also ensure the clusterrolebindings have unique names so they are not
clobbered

Bug 1625809 - Accept quoted APB broker_destroy_shared_resources arg

---

test/last_operation_bind.sh

Update test last bind operation to include the operation in validation.

add operation and param validation

---

build/Dockerfile-v3.10
build/Dockerfile-v3.11

- Uses the appropriate repo for the release
- Adds the gpg key for latest, since the forked repo may contain packages signed with the key from latest if they haven't been rebuilt since being forked.

Add dockerfiles for old releases

---

.travis.yml

This PR is meant to fix the broken Travis build 
https://travis-ci.org/openshift/ansible-service-broker/jobs/442720091
- golint changed upstream.
- [https://github.com/golang/lint/commit/5906](https://github.com/golang/lint/commit/5906)
related-to #1107 

💚 Get golint changed upstream.

---

.travis.yml
scripts/broker-ci/setup-cluster.sh
scripts/travis.sh

Just trying to see if travis will get fixed.

trying to fix travis

---

ansible_role/operator/cr.example.yaml
ansible_role/tasks/main.yml
ansible_role/templates/broker.deployment.yaml

Tweaks to support operators built for OLM

Additional OLM support

---

ansible_role/tasks/main.yml

-client serviceaccount needs to exist before service catalog lookup

Fix APB/Operator ansible task order.

---

Gopkg.lock
Gopkg.toml
ansible_role/templates/broker-auth.clusterrole.yaml
vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go

Fixes Bug 1613280 - only create netpolicy if one already exists

Update to bundle-lib 0.2.15 to fix net-policy issue

---

Gopkg.lock
Gopkg.toml
apb/templates/broker-auth.clusterrole.yaml
vendor/github.com/automationbroker/bundle-lib/.travis.yml
vendor/github.com/automationbroker/bundle-lib/crd/conversions.go
vendor/github.com/automationbroker/bundle-lib/crd/conversions_test.go
vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go

Fixes Bug 1613280 - only create netpolicy if one already exists

Update to bundle-lib 0.1.9 to fix net-policy issue

---

Makefile
ansible_role/handlers/main.yml
ansible_role/tasks/build_config.yml
ansible_role/tasks/main.yml
build/Dockerfile-openshift

Setting up the first of some basic tests for our operators in Prow CI

add operator linting and openshift CI make tasks

---

OWNERS

Totally a power play on my part.

Add djzager to OWNERS

---

Gopkg.lock
Gopkg.toml
vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client.go

Brings in bundle-lib latest release

bundle-lib 0.2.16 release

---

Makefile

The bot merged the PR with the new operator changes despite a hold on it, so this will at least revert to the previous operator build until we can stabilize the new operator content for OLM.

Use old operator builds until new one stabalizes

---

operator/deploy/olm-catalog/0.2.0/admin.clusterrolebinding.yaml
operator/roles/ansible-service-broker/defaults/main.yml
operator/roles/ansible-service-broker/tasks/main.yml
operator/roles/ansible-service-broker/templates/broker-admin.clusterrolebinding.yaml.j2
operator/roles/ansible-service-broker/templates/broker-config.configmap.yaml.j2
operator/roles/ansible-service-broker/templates/broker-user-auth.clusterrole.yaml.j2

* Adds the CRB for OLM to grant the operator admin
* Adds the CRB for the operator to grant the broker admin
* Adds the aggregation rule for user authorization via the broker

Add more operator related RBAC

---

pkg/runtime/runtime.go

In a previous patch we added code to only create a network
policy if there were other network policies. Otherwise, leave
it open. But during the DestroySandbox, we blindly try to
delete the network policies which we didn't create.

Bug 1643303 - only delete netpol if they exist

---

operator/deploy/olm-catalog/0.2.0/automationbrokeroperator.v0.2.0.clusterserviceversion.yaml

Update CSV based on community-operators PR

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/1.0.0/openshiftansibleservicebroker.v1.0.0.clusterserviceversion.yaml

Makes the downstream automation broker default correct.

update csv to get the correct example for downstream images

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/1.0.0/openshiftansibleservicebroker.v1.0.0.clusterserviceversion.yaml

Fixing pull policy for downstream CSV

Bug 1689787 -update image pull policy to ifNotPresent

---

OWNERS

Trying to get a handle on my github notifications and the robot keeps adding me to PRs.

Remove eriknelson from OWNERS

---

operator/deploy/crds/osb_v1alpha1_automationbroker_cr.yaml
operator/deploy/crds/osb_v1alpha1_automationbroker_crd.yaml
operator/deploy/operator.yaml
operator/deploy/role_binding.yaml
operator/deploy/service_account.yaml
operator/molecule/default/asserts.yml
operator/molecule/default/molecule.yml
operator/molecule/default/playbook.yml
operator/molecule/default/prepare.yml
operator/molecule/test-cluster/molecule.yml
operator/molecule/test-cluster/playbook.yml
operator/molecule/test-local/asserts.yml
operator/molecule/test-local/molecule.yml
operator/molecule/test-local/playbook.yml
operator/molecule/test-local/prepare.yml

You will need to have helm installed and run this steps:
`helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com`
- update cr/crds
- add molecule testing for local scenario
- 

adding molecule tests for local testing

---

operator/build/molecule.Dockerfile

Makes it so the molecule binary is in the PATH in the molecule container

fix path for molecule binary in container

---

operator/build/entrypoint.sh
operator/build/molecule.Dockerfile

Sets the permissions on the local python directories so that we can import the needed molecule libraries.

Make sure we can access the installed python libraries

---

operator/molecule/cluster/molecule.yml
operator/molecule/cluster/playbook.yml

* Adds ability to get built operator from the operator image env var `IMAGE_FORMAT`.

Fabian cluster scenario

---

operator/molecule/cluster-olm/playbook.yml
operator/molecule/cluster-olm/prepare.yml
operator/molecule/cluster/molecule.yml
operator/molecule/cluster/playbook.yml
operator/molecule/cluster/verify.yml

This adds tests for the e2e cluster test
- adding verify steps that create/delete service instances and bindings
- moving subscription creation after service catalog is installed

Adding ASB e2e functional tests

---

operator/deploy/crds/osb_v1_automationbroker_cr.yaml
operator/deploy/crds/osb_v1_automationbroker_crd.yaml
operator/deploy/olm-catalog/automationbroker-manifests/0.2.0/automationbroker.crd.yaml
operator/deploy/olm-catalog/automationbroker-manifests/0.2.0/automationbrokeroperator.v0.2.0.clusterserviceversion.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1.0/automationbroker.crd.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1.0/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
operator/molecule/cluster-olm/playbook.yml
operator/molecule/cluster/playbook.yml
operator/molecule/cluster/prepare.yml
operator/molecule/cluster/verify.yml
operator/molecule/test-cluster/playbook.yml
operator/molecule/test-local/playbook.yml
operator/molecule/test-local/prepare.yml
operator/molecule/test-local/verify.yml
operator/roles/ansible-service-broker/tasks/main.yml
operator/roles/ansible-service-broker/templates/broker.automationbroker.yaml.j2
operator/watches.yaml

Moving api version for AutomationBroker to v1

bump version to v1

---

build/custom-ci-build-root.Dockerfile

Fixing CI custom build root 

---

Gopkg.lock
Gopkg.toml
vendor/github.com/automationbroker/bundle-lib/registries/adapters/quay_adapter.go
vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go

Reverts openshift/ansible-service-broker#1180

Revert "Bug 1643303 - Fixed in bundle-lib 0.2.17

---

scripts/run_latest_build.sh

Bug 1213 - Link to last known version of install.yaml

---

Gopkg.lock
Gopkg.toml
vendor/github.com/automationbroker/bundle-lib/registries/adapters/quay_adapter.go
vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go

Reverts openshift/ansible-service-broker#1219
to add back fixes for bug 1643303

Adds back "Bug 1643303 - Fixed in bundle-lib 0.2.17"

---

Gopkg.lock
Gopkg.toml
vendor/github.com/automationbroker/bundle-lib/registries/adapters/quay_adapter.go
vendor/github.com/automationbroker/bundle-lib/runtime/runtime.go

Reverts openshift/ansible-service-broker#1221

Revert "Bug 1643303 - Add back Fixed in bundle-lib 0.2.17 (#1219)" (#1…"

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/package.yaml
operator/molecule/cluster-olm/prepare.yml

Updates the CSV for z stream release

Bug 1717623 - 4.1.0 -> 4.1.1

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml

* Adding a file for ART so that replacement of values in the CSV and package files can be completed

Adding art replacement file

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml

typo in the current csv version

---

build/Dockerfile-ubi
build/entrypoint.sh
operator/roles/ansible-service-broker/templates/broker-config.configmap.yaml.j2

Move to a single dockerfile for upstream and downstream building. Will remove the need for RPMs
* creates broker/dashboard-redirector binaries
* adds them to the image
* NOTE: need to update the config to default to /tmp/asb.log because we
don't have permissions to /var/log
/hold

adding UBI dockerfile

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/automationbroker.crd.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/bundle.crd.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/bundlebindings.crd.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/bundleinstances.crd.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/image-references
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/openshiftansibleservicebroker.v4.2.0.clusterserviceversion.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/package.yaml
operator/molecule/cluster-olm/molecule.yml
operator/molecule/cluster-olm/prepare.yml

Creating 4.2 folder updating csv's and testing to use 4.2.

adding 4.2 csv and updating package and art files

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/openshiftansibleservicebroker.v4.2.0.clusterserviceversion.yaml

Fixes validations that are causing entire redhat operators to be unable to release.
-
-
-

Bug 1732557: Fixing CSV validations

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml

Fixes validations that are causing entire redhat operators to be unable to release.
-
-
-

Bug 1732559: Fixing CSV validations for the CVP checks

---

Gopkg.lock
Gopkg.toml
docs/config.md
pkg/app/app.go
vendor/github.com/automationbroker/bundle-lib/Gopkg.lock
vendor/github.com/automationbroker/bundle-lib/registries/adapters/adapter.go
vendor/github.com/automationbroker/bundle-lib/registries/adapters/dockerhub_adapter.go
vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client.go
vendor/github.com/automationbroker/bundle-lib/registries/adapters/oauth/client_test.go
vendor/github.com/automationbroker/bundle-lib/registries/adapters/openshift_adapter.go
vendor/github.com/automationbroker/bundle-lib/registries/adapters/partner_rhcc_adapter.go
vendor/github.com/automationbroker/bundle-lib/registries/adapters/rhcc_adapter.go
vendor/github.com/automationbroker/bundle-lib/registries/adapters/rhcc_adapter_test.go
vendor/github.com/automationbroker/bundle-lib/registries/registry.go

Fixes Bug 1696113 by updating to bundle-lib 0.1.11, which adds oauth and skip_verify_ssl support. Also adds skip_verify_ssl support config initialization.

Bug 1696113 add oauth and skip_verify_ssl support

---

operator/build/Dockerfile

Run user_setup if it's still present

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/openshiftansibleservicebroker.v4.2.0.clusterserviceversion.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/openshiftansibleservicebroker.v4.3.0.clusterserviceversion.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml

Adds skipRanges to the CSVs and art.yaml, which should allow for proper upgrades across versions.
https://bugzilla.redhat.com/show_bug.cgi?id=1772392

Bug 1772392: Add olm.skipRange to all CSVs and art.yaml

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/openshiftansibleservicebroker.v4.3.0.clusterserviceversion.yaml
operator/roles/ansible-service-broker/templates/broker-operator.monitor-role.yaml.j2

also remove TODO comment left over from previous PR
https://github.com/openshift/ansible-service-broker/pull/1256/files#r345233931

Bug 1782058: Allow ASBO to access endpoints

---

operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.3/openshiftansibleservicebroker.v4.3.0.clusterserviceversion.yaml
operator/roles/ansible-service-broker/templates/broker-operator.monitor-role.yaml.j2

also remove TODO comment left over from previous PR
https://github.com/openshift/ansible-service-broker/pull/1256/files#r345233931

Bug 1776135: Allow ASBO to access endpoints

---

build/custom-ci-build-root.Dockerfile
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/openshiftansibleservicebroker.v4.2.0.clusterserviceversion.yaml
operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/art.yaml

* Bug 1772392: Add olm.skipRange to all CSVs and art.yaml
* Properly set skipRange for 4.1
(cherry picked from commit d8cb6fe7bdeef19b888aa9a01e02701e356f630f)
-
-
-

Bug 1772743: Add olm.skipRange to all CSVs and art.yaml (#1257)

---

Makefile
build/custom-ci-build-root.Dockerfile
cmd/dashboard-redirector/main.go
pkg/broker/broker.go

- Apply the same changes to fix make target vet and test
- Upgrade the docker file to use python3 and molecule 2.22
**Moivation**
Fix ansible moelcule ci jobs

Fix broken CI
